# Combined module: core_pipeline.py
# This file was automatically generated by combining multiple smaller utilities.


# ==================================================
# From: capability_matrix.py
# ==================================================

"""
Capability Matrix & Data Quality Report Module
Determines which analyses are mathematically feasible based on available canonical fields.
Follows strict graceful degradation — never fabricates missing data.
"""

from typing import Dict, Any, List

from tools.base_tool import EXTENDED_CLINICAL_FEATURES


class CapabilityMatrix:
    """
    Evaluates dataset schema and data quality to produce a machine-readable capability matrix.
    """

    def evaluate_capabilities(self, canonical_mapping: Dict[str, str], profile: Dict[str, Any]) -> Dict[str, Any]:
        """
        Evaluates which ML analysis tools can be executed on this dataset.
        """
        # Invert canonical mapping: canonical_field -> list of source column names
        canonical_to_source = {}
        for src, can in canonical_mapping.items():
            if can != "OTHER":
                canonical_to_source.setdefault(can, []).append(src)

        available_fields = list(canonical_to_source.keys())
        missing_fields = [f for f in ["DRUG", "DATE", "PATIENT_ID", "DIAGNOSIS", "AGE", "GENDER", "DOSAGE", "REGION", "QUANTITY", "PRESCRIBER", "RISK_SCORE"] if f not in available_fields]
        
        quality_warnings = []
        missing_rate = profile.get("missing_rate_pct", 0)
        if missing_rate > 15:
            quality_warnings.append(f"High overall dataset missing rate ({missing_rate}%). Certain statistical inferences may have wider confidence intervals.")
            
        row_count = profile.get("row_count", 0)
        if row_count < 30:
            quality_warnings.append(f"Small dataset size ({row_count} records). Machine learning models will employ cross-validation with regularized constraints.")

        # --- Evaluate Specific Capabilities ---
        capabilities = {}

        # 1. Trend & Forecasting Capability
        has_date = "DATE" in available_fields
        has_dynamic_numeric = any(
            canonical in (EXTENDED_CLINICAL_FEATURES | {"OTHER"})
            and source in profile.get("columns", {})
            and profile["columns"][source].get("is_numeric", False)
            for source, canonical in canonical_mapping.items()
        )
        has_measure = bool(set(available_fields).intersection({"QUANTITY", "DRUG", "PATIENT_ID"})) or has_dynamic_numeric
        if has_date and has_measure and row_count >= 5:
            capabilities["trend"] = {
                "feasible": True,
                "confidence": 0.95,
                "primary_date_col": canonical_to_source["DATE"][0],
                "models": ["Prophet", "ExponentialSmoothing (ETS)", "ARIMA", "LinearTrend"],
                "description": "Temporal trend evaluation, volume forecasting, and seasonal decomposition."
            }
        else:
            reasons = []
            if not has_date: reasons.append("Missing canonical 'DATE' field")
            if row_count < 5: reasons.append(f"Insufficient longitudinal depth ({row_count} rows)")
            capabilities["trend"] = {
                "feasible": False,
                "confidence": 0.0,
                "reason": " / ".join(reasons),
                "description": "Longitudinal forecasting unavailable due to missing temporal dimensions."
            }

        # 2. Cohort & Clustering Capability
        clustering_features = [f for f in available_fields if f in ["AGE", "QUANTITY", "DOSAGE", "DRUG", "GENDER", "REGION", "DIAGNOSIS", "RISK_SCORE"]]
        dynamic_feature_count = sum(
            1 for source, canonical in canonical_mapping.items()
            if canonical in (EXTENDED_CLINICAL_FEATURES | {"OTHER"})
            and source in profile.get("columns", {})
            and self._is_safe_dynamic_profile(profile["columns"][source], row_count)
        )
        if len(clustering_features) + dynamic_feature_count >= 2 and row_count >= 10:
            capabilities["cohort"] = {
                "feasible": True,
                "confidence": 0.92,
                "feature_count": len(clustering_features) + dynamic_feature_count,
                "features": clustering_features + (["OTHER"] if dynamic_feature_count else []),
                "models": ["KMeans", "DBSCAN", "AgglomerativeClustering", "GaussianMixture"],
                "description": "Patient and prescription phenotypic clustering with metric-driven algorithm selection."
            }
        else:
            capabilities["cohort"] = {
                "feasible": False,
                "confidence": 0.0,
                "reason": f"Requires at least 2 cohort features (found {len(clustering_features) + dynamic_feature_count}) and >= 10 records.",
                "description": "Clustering unavailable due to insufficient dimensional features."
            }

        # 3. Anomaly Detection Capability
        has_numeric = bool(set(available_fields).intersection({"AGE", "QUANTITY", "DOSAGE", "RISK_SCORE"})) or any(p.get("is_numeric", False) for p in profile.get("columns", {}).values())
        if has_numeric and row_count >= 10:
            capabilities["anomaly"] = {
                "feasible": True,
                "confidence": 0.90,
                "models": ["IsolationForest", "LocalOutlierFactor (LOF)", "OneClassSVM", "Statistical Z-Score"],
                "description": "Outlier detection for unusual dosing, abnormal prescribing volume, and risk anomalies."
            }
        else:
            capabilities["anomaly"] = {
                "feasible": False,
                "confidence": 0.0,
                "reason": "Requires numeric distributions and >= 10 records.",
                "description": "Anomaly detection unavailable."
            }

        # 4. Risk Prediction Capability
        has_supervised_target = "RISK_SCORE" in available_fields
        if has_supervised_target and row_count >= 20:
            capabilities["risk"] = {
                "feasible": True,
                "mode": "supervised",
                "target_col": canonical_to_source["RISK_SCORE"][0],
                "models": ["XGBoost", "RandomForest", "GradientBoosting", "LogisticRegression"],
                "description": "Supervised clinical risk stratification with objective cross-validation."
            }
        elif len(clustering_features) + dynamic_feature_count >= 1 and row_count >= 10:
            capabilities["risk"] = {
                "feasible": True,
                "mode": "unsupervised_composite",
                "models": ["Multi-Factor Risk Index", "Isolation Risk Scorer"],
                "description": "Unsupervised composite risk index calculated from clinical dimensions (no explicit target label)."
            }
        else:
            capabilities["risk"] = {
                "feasible": False,
                "confidence": 0.0,
                "reason": "Insufficient features or sample size for risk stratification.",
                "description": "Risk prediction unavailable."
            }

        # 5. Co-Prescribing & Pattern Analysis
        has_patient = "PATIENT_ID" in available_fields
        has_drug = "DRUG" in available_fields
        if (has_patient and has_drug and row_count >= 10) or (has_drug and row_count >= 20):
            capabilities["pattern"] = {
                "feasible": True,
                "confidence": 0.88,
                "models": ["Apriori Association Rules", "FP-Growth", "Co-occurrence Matrix"],
                "description": "Polypharmacy interaction patterns, frequent itemsets, and sequential prescribing rules."
            }
        else:
            capabilities["pattern"] = {
                "feasible": False,
                "confidence": 0.0,
                "reason": "Requires DRUG and PATIENT_ID fields for association rule mining.",
                "description": "Co-prescribing pattern analysis unavailable."
            }

        feasible_count = sum(1 for c in capabilities.values() if c.get("feasible", False))

        return {
            "available_canonical_fields": available_fields,
            "missing_canonical_fields": missing_fields,
            "canonical_to_source_mapping": canonical_to_source,
            "quality_warnings": quality_warnings,
            "capabilities": capabilities,
            "feasible_analysis_count": feasible_count,
            "total_supported_analyses": len(capabilities)
        }

    @staticmethod
    def _is_safe_dynamic_profile(column_profile: Dict[str, Any], row_count: int) -> bool:
        if column_profile.get("is_date") or column_profile.get("unique_count", 0) <= 1:
            return False
        if column_profile.get("is_numeric"):
            return True
        unique_count = column_profile.get("unique_count", 0)
        return 2 <= unique_count <= min(50, max(10, int(max(row_count, 1) * 0.2)))



# ==================================================
# From: intelligent_analyzer.py
# ==================================================

"""
Intelligent Data Analyzer Integration Module
Integrates the SchemaAnalyzer with the existing healthcare analytics pipeline.
"""

import pandas as pd
import numpy as np
from typing import Dict, List, Any, Tuple
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from utils.data_profiling import SchemaAnalyzer, ColumnType
import warnings
import logging

logger = logging.getLogger(__name__)


class IntelligentAnalyzer:
    """
    Integration layer for intelligent data analysis in healthcare systems.
    
    This class provides a clean interface to use the SchemaAnalyzer
    within the existing ML pipeline while preventing common data type errors.
    """
    
    def __init__(self):
        self.schema_analyzer = SchemaAnalyzer()
        self.last_analysis = None
        self.validation_errors = []
    
    def safe_mean(self, series: pd.Series, column_name: str) -> float:
        """
        Safely compute mean only for numerical columns.
        
        Args:
            series: Pandas Series
            column_name: Name of the column
            
        Returns:
            Mean value or raises error for non-numerical columns
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type == ColumnType.NUMERICAL:
            return pd.to_numeric(series, errors='coerce').mean()
        else:
            error_msg = f"Cannot compute mean on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def safe_std(self, series: pd.Series, column_name: str) -> float:
        """
        Safely compute standard deviation only for numerical columns.
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type == ColumnType.NUMERICAL:
            return pd.to_numeric(series, errors='coerce').std()
        else:
            error_msg = f"Cannot compute std on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def safe_median(self, series: pd.Series, column_name: str) -> float:
        """
        Safely compute median only for numerical columns.
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type == ColumnType.NUMERICAL:
            return pd.to_numeric(series, errors='coerce').median()
        else:
            error_msg = f"Cannot compute median on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def safe_mode(self, series: pd.Series, column_name: str) -> Any:
        """
        Safely compute mode for categorical or numerical columns.
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type in [ColumnType.CATEGORICAL, ColumnType.NUMERICAL, ColumnType.BOOLEAN]:
            return series.mode().iloc[0] if not series.mode().empty else None
        else:
            error_msg = f"Cannot compute mode on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def safe_value_counts(self, series: pd.Series, column_name: str) -> pd.Series:
        """
        Safely compute value counts for categorical columns.
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type == ColumnType.CATEGORICAL:
            return series.value_counts()
        else:
            error_msg = f"Cannot compute value_counts on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def safe_distribution(self, series: pd.Series, column_name: str) -> Dict[str, float]:
        """
        Safely compute distribution percentages for categorical and boolean columns.
        """
        col_type = self.schema_analyzer.detect_column_type(series, column_name)
        
        if col_type == ColumnType.CATEGORICAL:
            value_counts = series.value_counts()
            total = len(series.dropna())
            return (value_counts / total * 100).round(2).to_dict()
        elif col_type == ColumnType.BOOLEAN:
            # Handle boolean columns specially
            value_counts = series.value_counts()
            total = len(series.dropna())
            return (value_counts / total * 100).round(2).to_dict()
        else:
            error_msg = f"Cannot compute distribution on {col_type.value} column '{column_name}'"
            self.validation_errors.append(error_msg)
            logger.warning(error_msg)
            raise ValueError(error_msg)
    
    def analyze_dataframe_intelligently(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Perform intelligent analysis on the entire dataframe.
        
        Args:
            df: Pandas DataFrame to analyze
            
        Returns:
            Comprehensive analysis results with type-safe operations
        """
        self.validation_errors.clear()
        results = self.schema_analyzer.analyze_dataframe(df)
        self.last_analysis = results
        
        # Add safe operation examples
        results['safe_operations_demo'] = self._demonstrate_safe_operations(df)
        
        return results
    
    def _demonstrate_safe_operations(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Demonstrate safe operations on different column types.
        """
        demo_results = {}
        
        for column_name in df.columns:
            column = df[column_name]
            col_type = self.schema_analyzer.detect_column_type(column, column_name)
            
            demo_results[column_name] = {
                'detected_type': col_type.value,
                'safe_operations': []
            }
            
            try:
                if col_type == ColumnType.NUMERICAL:
                    mean_val = self.safe_mean(column, column_name)
                    demo_results[column_name]['safe_operations'].append(f"Mean: {mean_val:.2f}")
                    
                    std_val = self.safe_std(column, column_name)
                    demo_results[column_name]['safe_operations'].append(f"Std: {std_val:.2f}")
                    
                    median_val = self.safe_median(column, column_name)
                    demo_results[column_name]['safe_operations'].append(f"Median: {median_val:.2f}")
                
                elif col_type == ColumnType.CATEGORICAL:
                    if 'gender' in column_name.lower():
                        dist = self.safe_distribution(column, column_name)
                        demo_results[column_name]['safe_operations'].append(f"Gender Distribution: {dist}")
                    else:
                        mode_val = self.safe_mode(column, column_name)
                        demo_results[column_name]['safe_operations'].append(f"Mode: {mode_val}")
                        
                        value_counts = self.safe_value_counts(column, column_name)
                        demo_results[column_name]['safe_operations'].append(f"Value counts: {dict(value_counts.head(3))}")
                
                elif col_type == ColumnType.BOOLEAN:
                    dist = self.safe_distribution(column, column_name)
                    demo_results[column_name]['safe_operations'].append(f"Boolean Distribution: {dist}")
                
                elif col_type == ColumnType.DATETIME:
                    demo_results[column_name]['safe_operations'].append("Date range analysis")
                
            except Exception as e:
                demo_results[column_name]['safe_operations'].append(f"Error: {str(e)}")
        
        return demo_results
    
    def get_validation_errors(self) -> List[str]:
        """Get all validation errors that occurred."""
        return self.validation_errors
    
    def get_column_summary(self, df: pd.DataFrame, column_name: str) -> Dict[str, Any]:
        """
        Get a comprehensive summary of a specific column.
        """
        if column_name not in df.columns:
            return {"error": f"Column '{column_name}' not found"}
        
        return self.schema_analyzer.analyze_column(df[column_name], column_name)
    
    def suggest_data_quality_improvements(self, df: pd.DataFrame) -> List[str]:
        """
        Suggest improvements based on data quality analysis.
        """
        suggestions = []
        analysis = self.analyze_dataframe_intelligently(df)
        
        # Check for high missing values
        for col_name, col_analysis in analysis['column_analysis'].items():
            if 'missing' in col_analysis and 'count' in col_analysis:
                missing_pct = (col_analysis['missing'] / col_analysis['count']) * 100
                if missing_pct > 20:
                    suggestions.append(f"Column '{col_name}' has {missing_pct:.1f}% missing values - consider imputation")
        
        # Check for potential type mismatches
        for col_name, col_analysis in analysis['column_analysis'].items():
            if col_analysis.get('type') == 'unknown':
                suggestions.append(f"Column '{col_name}' has unknown type - review data format")
        
        # Gender-specific suggestions
        for col_name, col_analysis in analysis['column_analysis'].items():
            if 'gender' in col_name.lower() and col_analysis.get('type') == 'categorical':
                dist = col_analysis.get('distribution', {})
                if len(dist) > 2:
                    suggestions.append(f"Gender column '{col_name}' has {len(dist)} categories - consider standardizing")
        
        return suggestions


def create_integration_example():
    """Create example showing integration with existing ML pipeline."""
    
    # Sample healthcare data
    np.random.seed(42)
    n_records = 500
    
    data = {
        'patient_id': range(1, n_records + 1),
        'age': np.random.randint(18, 85, n_records),
        'gender': np.random.choice(['Male', 'Female'], n_records),
        'diagnosis': np.random.choice(['Hypertension', 'Diabetes', 'Asthma'], n_records),
        'drug_name': np.random.choice(['Metformin', 'Lisinopril', 'Aspirin'], n_records),
        'dosage': np.random.normal(100, 25, n_records),
        'admission_date': pd.date_range('2023-01-01', periods=n_records, freq='h'),
        'emergency_visit': np.random.choice([True, False], n_records, p=[0.2, 0.8]),
    }
    
    df = pd.DataFrame(data)
    
    # Initialize intelligent analyzer
    analyzer = IntelligentAnalyzer()
    
    # Perform intelligent analysis
    results = analyzer.analyze_dataframe_intelligently(df)
    
    print("=" * 80)
    print("INTELLIGENT HEALTHCARE DATA ANALYSIS")
    print("=" * 80)
    
    print(f"\nSchema Overview: {results['schema_overview']['type_distribution']}")
    
    print("\nSafe Operations Demonstration:")
    for col_name, demo in results['safe_operations_demo'].items():
        print(f"\n{col_name} ({demo['detected_type']}):")
        for op in demo['safe_operations']:
            print(f"  ✓ {op}")
    
    print("\nValidation Errors:", analyzer.get_validation_errors())
    
    print("\nData Quality Suggestions:")
    for suggestion in analyzer.suggest_data_quality_improvements(df):
        print(f"  • {suggestion}")
    
    return analyzer, results


if __name__ == "__main__":
    analyzer, results = create_integration_example()



# ==================================================
# From: medical_pipeline.py
# ==================================================

import pandas as pd
import numpy as np
import time
import json
import logging
from typing import Dict, List, Any, Tuple, Optional
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from utils.data_profiling import SemanticCategory, MEDICAL_ONTOLOGY
from utils.data_profiling import SchemaAnalyzer, ColumnType

logger = logging.getLogger(__name__)

class MedicalDataPipeline:
    """
    Strict 5-step pipeline for analyzing unknown medical datasets.
    """
    
    def __init__(self, df: pd.DataFrame):
        self.df = df
        self.column_mapping = {}
        self.preprocessed_df = None
        self.analysis_results = {}
        self.pipeline_stats = {
            "start_time": time.time(),
            "steps_completed": []
        }
        self.schema_analyzer = SchemaAnalyzer()

    # ==================================================
    # STEP 1: ADVANCED COLUMN UNDERSTANDING
    # ==================================================
    def step1_column_understanding(self) -> Dict[str, Any]:
        """
        Dynamically infer meaning using medical ontology.
        """
        logger.info("Step 1: Advanced Column Understanding")
        mapping_table = []
        
        for col in self.df.columns:
            # 1. Profiling
            series = self.df[col]
            dtype = str(series.dtype)
            unique_count = series.nunique()
            null_count = series.isnull().sum()
            sample_values = series.dropna().head(3).tolist()
            
            # 2. Semantic Mapping
            category, confidence, reasoning = self._map_to_category(col, series)
            
            self.column_mapping[col] = {
                "category": category,
                "confidence": confidence,
                "reasoning": reasoning,
                "dtype": dtype
            }
            
            mapping_table.append({
                "Column Name": col,
                "Data Type": dtype,
                "Assigned Category": category.value,
                "Confidence Score": round(confidence, 2),
                "Reasoning": reasoning
            })
            
        self.pipeline_stats["steps_completed"].append("STEP 1: COLUMN UNDERSTANDING")
        return pd.DataFrame(mapping_table)

    def _map_to_category(self, col_name: str, series: pd.Series) -> Tuple[SemanticCategory, float, str]:
        """
        Logic for semantic category mapping.
        """
        col_lower = col_name.lower()
        best_cat = SemanticCategory.UNKNOWN
        max_score = 0.0
        reasoning = "No reliable mapping possible."

        # Strategy 1: Keyword Matching
        for cat, info in MEDICAL_ONTOLOGY.items():
            score = 0.0
            matched_keywords = []
            for kw in info["keywords"]:
                if kw in col_lower:
                    score += 0.5
                    matched_keywords.append(kw)
            
            if score > max_score:
                max_score = score
                best_cat = cat
                reasoning = f"Matched keywords: {', '.join(matched_keywords)}"

        # Strategy 2: Value Range / Domain Heuristics
        if pd.api.types.is_numeric_dtype(series):
            # BP check
            if "bp" in col_lower or "systolic" in col_lower or "diastolic" in col_lower:
                if series.median() > 60 and series.median() < 200:
                    best_cat = SemanticCategory.VITAL_SIGNS
                    max_score = max(max_score, 0.9)
                    reasoning = "Numeric range (60-200) and name suggest blood pressure."
            
            # Heart rate check
            if "hr" in col_lower or "pulse" in col_lower:
                if series.median() > 40 and series.median() < 220:
                    best_cat = SemanticCategory.VITAL_SIGNS
                    max_score = max(max_score, 0.9)
                    reasoning = "Numeric range (40-220) and name suggest heart rate."

            # Age check
            if "age" in col_lower:
                if series.max() < 120:
                    best_cat = SemanticCategory.DEMOGRAPHICS
                    max_score = max(max_score, 0.95)
                    reasoning = "Numeric range (0-120) and name suggest patient age."

        # Strategy 3: Formatting (Dates)
        if best_cat == SemanticCategory.UNKNOWN:
            try:
                if self.schema_analyzer._is_datetime_column(series, col_name):
                    best_cat = SemanticCategory.TEMPORAL
                    max_score = 0.8
                    reasoning = "Values conform to datetime patterns."
            except:
                pass

        # Final adjustments
        if max_score > 1.0: max_score = 1.0
        if max_score < 0.3:
            best_cat = SemanticCategory.UNKNOWN
            reasoning = "Low confidence in categorical/numeric mapping."

        return best_cat, max_score, reasoning

    # ==================================================
    # STEP 2: DATA PREPROCESSING
    # ==================================================
    def step2_preprocessing(self) -> Dict[str, Any]:
        """
        Handle missing values, normalize, and encode.
        """
        logger.info("Step 2: Data Preprocessing")
        df_clean = self.df.copy()
        preprocessing_log = []

        for col in df_clean.columns:
            series = df_clean[col]
            cat = self.column_mapping[col]["category"]
            
            # Handle missing values
            if series.isnull().any():
                if pd.api.types.is_numeric_dtype(series):
                    df_clean[col] = series.fillna(series.median())
                    preprocessing_log.append(f"Imputed '{col}' with median.")
                else:
                    df_clean[col] = series.fillna(series.mode()[0] if not series.mode().empty else "UNKNOWN")
                    preprocessing_log.append(f"Imputed '{col}' with mode.")

            # Normalize numeric features (except IDs and dates)
            if pd.api.types.is_numeric_dtype(series) and cat not in [SemanticCategory.IDENTIFIERS, SemanticCategory.TEMPORAL]:
                scaler = StandardScaler()
                df_clean[col] = scaler.fit_transform(df_clean[[col]])
                preprocessing_log.append(f"Normalized '{col}'.")

            # Encode categorical features
            if not pd.api.types.is_numeric_dtype(series) and cat not in [SemanticCategory.CLINICAL_NOTES, SemanticCategory.TEMPORAL]:
                le = LabelEncoder()
                df_clean[col] = le.fit_transform(df_clean[col].astype(str))
                preprocessing_log.append(f"Encoded '{col}'.")

        self.preprocessed_df = df_clean
        self.pipeline_stats["steps_completed"].append("STEP 2: PREPROCESSING")
        return {"preprocessing_log": preprocessing_log}

    # ==================================================
    # STEP 3: AGENT EXECUTION (Orchestration)
    # ==================================================
    def step3_agent_execution(self, agents_config: Dict[str, bool]) -> Dict[str, Any]:
        """
        Execute specialized agents using mapped semantic categories.
        """
        logger.info("Step 3: Agent Execution")
        results = {}
        
        # Helper to get columns by category
        def get_cols(category: SemanticCategory):
            return [col for col, info in self.column_mapping.items() if info["category"] == category]

        # 1. RiskAgent
        if agents_config.get("risk", True):
            from agents.risk_agent_improved import run_risk_agent_improved
            # Map column categories to the agent's expected simplified col_map
            simplified_map = {}
            for col, info in self.column_mapping.items():
                cat = info["category"]
                if cat == SemanticCategory.IDENTIFIERS: simplified_map[col] = "patient_id"
                elif cat == SemanticCategory.MEDICATIONS: simplified_map[col] = "drug_name"
                elif cat == SemanticCategory.TEMPORAL: simplified_map[col] = "date"
                elif cat == SemanticCategory.DEMOGRAPHICS and "age" in col.lower(): simplified_map[col] = "age"
                elif cat == SemanticCategory.DIAGNOSIS: simplified_map[col] = "diagnosis"
                else: simplified_map[col] = "other"
            
            results["risk"] = run_risk_agent_improved(self.df, simplified_map)

        # 2. CohortAgent
        if agents_config.get("cohort", True):
            from agents.cohort_agent_advanced import run_cohort_agent_advanced
            results["cohort"] = run_cohort_agent_advanced(self.df, simplified_map)

        # 3. AnomalyAgent
        if agents_config.get("anomaly", True):
            from agents.anomaly_agent_improved import run_anomaly_agent_improved
            results["anomaly"] = run_anomaly_agent_improved(self.df, simplified_map)

        # 4. TrendAgent
        temporal_cols = get_cols(SemanticCategory.TEMPORAL)
        if agents_config.get("trend", True) and temporal_cols:
            from agents.trend_agent import run_trend_agent
            results["trend"] = run_trend_agent(self.df, simplified_map)

        # 5. PatternAgent
        if agents_config.get("pattern", True):
            from agents.pattern_agent import run_pattern_agent
            results["pattern"] = run_pattern_agent(self.df, simplified_map)

        self.analysis_results = results
        self.pipeline_stats["steps_completed"].append("STEP 3: AGENT EXECUTION")
        return results

    # ==================================================
    # STEP 4: PERFORMANCE & QUALITY EVALUATION
    # ==================================================
    def step4_evaluation(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """
        Unsupervised evaluation and multi-agent statistical validation.
        """
        logger.info("Step 4: Evaluation")
        eval_metrics = {}
        
        # Analysis Confidence Score calculation
        completeness = 1.0 - (self.df.isnull().sum().sum() / self.df.size)
        mapping_confidence = np.mean([info["confidence"] for info in self.column_mapping.values()])
        
        analysis_confidence = (completeness * 0.4) + (mapping_confidence * 0.6)
        
        eval_metrics["Analysis Confidence Score"] = round(analysis_confidence, 2)
        eval_metrics["Data Completeness"] = round(completeness, 2)
        
        # Multi-agent Statistical Validation
        try:
            from utils.agent_performance_validator import validate_agent_performance
            validation_results = validate_agent_performance(results)
            eval_metrics["statistical_validation"] = validation_results
            logger.info("Multi-agent statistical validation completed")
        except Exception as e:
            logger.error(f"Statistical validation failed: {e}")
            eval_metrics["statistical_validation"] = None
            
        eval_metrics["Ontology Match Rate"] = round(len([c for c in self.column_mapping.values() if c["category"] != SemanticCategory.UNKNOWN]) / len(self.column_mapping), 2)
        
        self.pipeline_stats["steps_completed"].append("STEP 4: EVALUATION")
        return eval_metrics

    # ==================================================
    # STEP 5: FINAL OUTPUT GENERATION
    # ==================================================
    def step5_final_report(self) -> Dict[str, Any]:
        """
        Structured final report.
        """
        return {
            "summary": {
                "rows": len(self.df),
                "cols": len(self.df.columns),
                "steps": self.pipeline_stats["steps_completed"]
            },
            "mapping": self.column_mapping,
            "results": self.analysis_results
        }



# ==================================================
# From: orchestrator.py
# ==================================================

"""
Orchestrator & AI Supervisor Planner Module
Plans tool execution based on intent + capability matrix, executes independent tools concurrently,
and handles dependency chains.
"""

import asyncio
import time
import concurrent.futures
import pandas as pd
from typing import Dict, Any, List, Optional, Callable

from tools.tool_registry import ToolRegistry
# Removed internal import


class AgentOrchestrator:
    """
    AI Supervisor / Planner & Execution Orchestrator.
    """

    def __init__(self, registry: Optional[ToolRegistry] = None):
        self.registry = registry or ToolRegistry()
        self.capability_evaluator = CapabilityMatrix()

    def plan_execution(
        self,
        query: str,
        capabilities_report: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Creates an intelligent execution plan based on user intent and dataset capabilities.
        """
        q_lower = query.lower() if query else ""
        caps = capabilities_report.get("capabilities", {})

        # Intent detection
        selected_tools = []
        if not q_lower or any(w in q_lower for w in ["all", "comprehensive", "full", "complete", "everything", "analyze"]):
            # Run all feasible tools
            for t_name in ["trend", "cohort", "risk", "anomaly", "pattern"]:
                if caps.get(t_name, {}).get("feasible", False):
                    selected_tools.append(t_name)
        else:
            if any(w in q_lower for w in ["trend", "forecast", "future", "longitudinal", "time", "prediction", "growth"]):
                if caps.get("trend", {}).get("feasible", False): selected_tools.append("trend")
            if any(w in q_lower for w in ["cohort", "cluster", "segment", "group", "phenotype"]):
                if caps.get("cohort", {}).get("feasible", False): selected_tools.append("cohort")
            if any(w in q_lower for w in ["risk", "hazard", "severity", "high risk", "adverse"]):
                if caps.get("risk", {}).get("feasible", False): selected_tools.append("risk")
            if any(w in q_lower for w in ["anomaly", "outlier", "unusual", "abnormal", "fraud", "deviation"]):
                if caps.get("anomaly", {}).get("feasible", False): selected_tools.append("anomaly")
            if any(w in q_lower for w in ["pattern", "interaction", "co-prescrib", "polypharmacy", "association", "combination"]):
                if caps.get("pattern", {}).get("feasible", False): selected_tools.append("pattern")

        # Fallback: if no specific intent matched, include all feasible tools
        if not selected_tools:
            selected_tools = [t for t, c in caps.items() if c.get("feasible", False)]

        # Define dependency stages (Independent tools in Stage 1, dependent tools in Stage 2)
        stage_1_tools = [t for t in selected_tools if t in ["trend", "cohort", "risk", "anomaly"]]
        stage_2_tools = [t for t in selected_tools if t not in stage_1_tools]

        return {
            "query": query,
            "selected_tools": selected_tools,
            "execution_stages": [
                {"stage": 1, "type": "concurrent_independent", "tools": stage_1_tools},
                {"stage": 2, "type": "dependent_sequential", "tools": stage_2_tools}
            ],
            "total_tools": len(selected_tools)
        }

    def execute_plan(
        self,
        df: pd.DataFrame,
        canonical_map: Dict[str, str],
        plan: Dict[str, Any],
        progress_callback: Optional[Callable[[str, Dict[str, Any]], None]] = None
    ) -> Dict[str, Any]:
        """
        Executes tools in parallel according to the plan with real-time event notifications.
        """
        start_overall = time.time()
        results: Dict[str, Any] = {}

        stages = plan.get("execution_stages", [])

        for stage_info in stages:
            tools_to_run = stage_info.get("tools", [])
            if not tools_to_run:
                continue

            if stage_info.get("type") == "concurrent_independent" and len(tools_to_run) > 1:
                # Concurrent Execution via ThreadPool
                with concurrent.futures.ThreadPoolExecutor(max_workers=min(4, len(tools_to_run))) as executor:
                    future_to_tool = {}
                    for t_name in tools_to_run:
                        if progress_callback:
                            progress_callback("tool_started", {"tool": t_name})
                        f = executor.submit(self.registry.execute_tool, t_name, df, canonical_map)
                        future_to_tool[f] = t_name

                    for f in concurrent.futures.as_completed(future_to_tool):
                        t_name = future_to_tool[f]
                        try:
                            res = f.result()
                            results[t_name] = res
                            if progress_callback:
                                progress_callback("tool_completed", {"tool": t_name, "status": res.get("status", "success"), "winner_model": res.get("model", "")})
                        except Exception as e:
                            results[t_name] = {
                                "tool": t_name,
                                "model": "Failed",
                                "status": "error",
                                "warnings": [f"Execution error in {t_name}: {str(e)}"]
                            }
                            if progress_callback:
                                progress_callback("tool_completed", {"tool": t_name, "status": "error", "error": str(e)})
            else:
                # Sequential Execution
                for t_name in tools_to_run:
                    if progress_callback:
                        progress_callback("tool_started", {"tool": t_name})
                    res = self.registry.execute_tool(t_name, df, canonical_map, prior_results=results)
                    results[t_name] = res
                    if progress_callback:
                        progress_callback("tool_completed", {"tool": t_name, "status": res.get("status", "success"), "winner_model": res.get("model", "")})

        total_duration = round((time.time() - start_overall) * 1000, 2)

        return {
            "execution_plan": plan,
            "tool_results": results,
            "total_duration_ms": total_duration,
            "executed_tool_count": len(results)
        }


