# Combined module: data_profiling.py
# This file was automatically generated by combining multiple smaller utilities.


# ==================================================
# From: medical_ontology.py
# ==================================================

from enum import Enum
from typing import List, Dict, Any

class SemanticCategory(Enum):
    IDENTIFIERS = "A. IDENTIFIERS"
    DEMOGRAPHICS = "B. DEMOGRAPHICS"
    VITAL_SIGNS = "C. VITAL_SIGNS"
    LAB_RESULTS = "D. LAB_RESULTS"
    DIAGNOSIS = "E. DIAGNOSIS / CONDITIONS"
    MEDICATIONS = "F. MEDICATIONS / TREATMENTS"
    TEMPORAL = "G. TEMPORAL DATA"
    IMAGING = "H. IMAGING / REPORT REFERENCES"
    CLINICAL_NOTES = "I. CLINICAL NOTES (TEXT)"
    UTILIZATION = "J. UTILIZATION / ADMINISTRATIVE"
    OUTCOMES = "K. OUTCOME-RELATED"
    DEVICE_DATA = "L. DEVICE / MONITORING DATA"
    GENOMIC = "M. GENOMIC / SPECIALIZED DATA"
    GENERAL = "N. GENERAL FEATURES"
    UNKNOWN = "O. UNKNOWN_MEDICAL_FEATURE"

MEDICAL_ONTOLOGY = {
    SemanticCategory.IDENTIFIERS: {
        "keywords": ["id", "mrn", "encounter", "visit_id", "record_id", "patient_id", "admission_id", "uid"],
        "description": "Unique identifiers for patients, visits, or records."
    },
    SemanticCategory.DEMOGRAPHICS: {
        "keywords": ["age", "gender", "sex", "ethnicity", "race", "weight", "height", "bmi", "dob", "birth"],
        "description": "Patient basic information."
    },
    SemanticCategory.VITAL_SIGNS: {
        "keywords": ["heart_rate", "pulse", "bp", "systolic", "diastolic", "temp", "spo2", "respiratory", "oxygen"],
        "description": "Basic physiological measurements."
    },
    SemanticCategory.LAB_RESULTS: {
        "keywords": ["glucose", "hba1c", "creatinine", "hemoglobin", "wbc", "platelets", "sodium", "potassium", "level", "result", "lab"],
        "description": "Laboratory test results."
    },
    SemanticCategory.DIAGNOSIS: {
        "keywords": ["icd", "diagnosis", "disease", "comorbidity", "condition", "status", "stage"],
        "description": "Medical conditions and diagnosis codes."
    },
    SemanticCategory.MEDICATIONS: {
        "keywords": ["drug", "medication", "dose", "frequency", "route", "prescription", "rx", "therapy"],
        "description": "Drugs, treatments, and dosages."
    },
    SemanticCategory.TEMPORAL: {
        "keywords": ["date", "time", "admission", "discharge", "timestamp", "start", "end", "duration"],
        "description": "Time-related data."
    },
    SemanticCategory.IMAGING: {
        "keywords": ["scan", "mri", "ct", "xray", "radiology", "imaging", "report", "dicom"],
        "description": "References to imaging or radiology reports."
    },
    SemanticCategory.CLINICAL_NOTES: {
        "keywords": ["note", "summary", "text", "description", "comment", "clinical", "history"],
        "description": "Free-text clinical observations."
    },
    SemanticCategory.UTILIZATION: {
        "keywords": ["stay", "cost", "billing", "insurance", "type", "department", "ward", "provider"],
        "description": "Administrative and hospital utilization data."
    },
    SemanticCategory.OUTCOMES: {
        "keywords": ["mortality", "death", "readmission", "outcome", "complication", "survival", "score"],
        "description": "Patient outcomes and complications."
    },
    SemanticCategory.DEVICE_DATA: {
        "keywords": ["ecg", "eeg", "monitor", "wearable", "signal", "icv", "stream"],
        "description": "Data from medical devices or wearables."
    },
    SemanticCategory.GENOMIC: {
        "keywords": ["gene", "biomarker", "dna", "rna", "marker", "mutation", "expression"],
        "description": "Genomic or specialized biomarker data."
    }
}



# ==================================================
# From: schema_analyzer.py
# ==================================================

"""
Intelligent Schema Analyzer for Healthcare Analytics
Automatically detects column types and applies appropriate statistical operations.
"""

import pandas as pd
import numpy as np
import warnings
from datetime import datetime
from typing import Dict, List, Tuple, Any, Optional
from enum import Enum
import logging
from collections import Counter

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ColumnType(Enum):
    """Enumeration for column data types."""
    NUMERICAL = "numerical"
    CATEGORICAL = "categorical"
    DATETIME = "datetime"
    BOOLEAN = "boolean"
    TEXT = "text"
    UNKNOWN = "unknown"


class SchemaAnalyzer:
    """
    Intelligent schema analyzer for healthcare data.
    
    Automatically detects column types and applies appropriate statistical operations
    based on data characteristics and healthcare domain knowledge.
    """
    
    def __init__(self):
        self.type_cache = {}
        self.operation_log = []
        
        # Healthcare-specific column patterns
        self.healthcare_patterns = {
            'categorical_keywords': {
                'gender', 'sex', 'diagnosis', 'drug', 'medication', 'treatment',
                'condition', 'symptom', 'specialty', 'department', 'hospital',
                'doctor', 'physician', 'patient_type', 'admission_type',
                'discharge_status', 'insurance', 'payment_method', 'ethnicity',
                'race', 'marital_status', 'religion', 'blood_type', 'rh_factor'
            },
            'datetime_keywords': {
                'date', 'time', 'admit', 'discharge', 'birth', 'appointment',
                'visit', 'created', 'updated', 'timestamp', 'dob', 'admission',
                'discharge_date', 'visit_date', 'prescription_date'
            },
            'boolean_keywords': {
                'active', 'inactive', 'alive', 'dead', 'survived', 'expired',
                'readmitted', 'emergency', 'urgent', 'elective', 'smoker',
                'pregnant', 'allergic', 'chronic', 'acute'
            }
        }
    
    def detect_column_type(self, column: pd.Series, column_name: str) -> ColumnType:
        """
        Intelligently detect the data type of a column.
        
        Args:
            column: Pandas Series to analyze
            column_name: Name of the column
            
        Returns:
            ColumnType enum value
        """
        # Check cache first
        cache_key = f"{column_name}_{len(column)}_{column.dtype}"
        if cache_key in self.type_cache:
            return self.type_cache[cache_key]
        
        # Remove missing values for analysis
        clean_series = column.dropna()
        
        if len(clean_series) == 0:
            detected_type = ColumnType.UNKNOWN
        else:
            # Check for boolean first (most specific)
            if self._is_boolean_column(clean_series, column_name):
                detected_type = ColumnType.BOOLEAN
            # Check for datetime next
            elif self._is_datetime_column(clean_series, column_name):
                detected_type = ColumnType.DATETIME
            # Check for numerical
            elif self._is_numerical_column(clean_series, column_name):
                detected_type = ColumnType.NUMERICAL
            # Check for categorical
            elif self._is_categorical_column(clean_series, column_name):
                detected_type = ColumnType.CATEGORICAL
            # Check for text
            elif self._is_text_column(clean_series, column_name):
                detected_type = ColumnType.TEXT
            else:
                detected_type = ColumnType.UNKNOWN
        
        # Cache the result
        self.type_cache[cache_key] = detected_type
        return detected_type
    
    def _is_datetime_column(self, series: pd.Series, column_name: str) -> bool:
        """Check if column contains datetime data."""
        # Check column name patterns first
        name_lower = column_name.lower()
        if any(keyword in name_lower for keyword in self.healthcare_patterns['datetime_keywords']):
            return True
        
        # Check pandas dtype first
        if pd.api.types.is_datetime64_any_dtype(series):
            return True
        
        # Skip if it's clearly numeric
        if pd.api.types.is_numeric_dtype(series):
            return False
        
        # Try to convert to datetime with better error handling
        try:
            # Check a sample first
            sample = series.head(10).dropna()
            if len(sample) == 0:
                return False
            
            # Only try conversion if it looks like a string date
            sample_str = sample.astype(str)
            # Look for date patterns in the sample
            date_patterns = ['-', '/', ':', ' AM', ' PM', 'T', 'Z']
            has_date_pattern = any(any(pattern in val for pattern in date_patterns) for val in sample_str)
            
            if has_date_pattern:
                converted = pd.to_datetime(sample, errors='coerce')
                if not converted.isna().all():
                    return True
        except:
            pass
        
        return False
    
    def _is_boolean_column(self, series: pd.Series, column_name: str) -> bool:
        """Check if column contains boolean data."""
    
        # Check column name patterns
        name_lower = column_name.lower()
        if any(keyword in name_lower for keyword in self.healthcare_patterns['boolean_keywords']):
            return True
        
        # Normalize values
        unique_values = set(series.astype(str).str.strip().str.lower().unique())
        
        # Strict boolean patterns only
        bool_patterns = {'true', 'false', 'yes', 'no', 'y', 'n', '1', '0', 't', 'f'}
        
        # ✅ FIX: require ALL values to be valid boolean patterns
        if len(unique_values) <= 2 and unique_values.issubset(bool_patterns):
            return True
        
        # Check pandas dtype
        if series.dtype == 'bool':
            return True
        
        return False
    
    def _is_numerical_column(self, series: pd.Series, column_name: str) -> bool:
        """Check if column contains numerical data."""
        # Check pandas dtype first
        if pd.api.types.is_numeric_dtype(series):
            # For integer columns, check if they could be categorical codes
            if series.dtype in ['int64', 'int32']:
                # If it's an ID column or has very few unique values, it might be categorical
                if 'id' in column_name.lower():
                    return False
                unique_ratio = series.nunique() / len(series)
                if unique_ratio <= 0.05:  # Less than 5% unique values suggests categorical
                    return False
            return True
        
        # Try to convert to numeric
        try:
            # Check a sample first
            sample = series.head(100).dropna()
            if len(sample) == 0:
                return False
            
            converted = pd.to_numeric(sample, errors='raise')
            # Check if conversion makes sense
            if converted.nunique() > 2:  # More than 2 unique values
                return True
        except:
            pass
        
        return False
    
    def _is_categorical_column(self, series: pd.Series, column_name: str) -> bool:
        """Check if column contains categorical data."""
        # Check column name patterns
        name_lower = column_name.lower()
        if any(keyword in name_lower for keyword in self.healthcare_patterns['categorical_keywords']):
            return True
        
        # Check string/object dtype
        if series.dtype == 'object' or series.dtype.name == 'category':
            return True
        
        # Check if numeric but with few unique values
        if pd.api.types.is_numeric_dtype(series):
            unique_ratio = series.nunique() / len(series)
            if unique_ratio <= 0.05:  # Less than 5% unique values suggests categorical
                return True
        
        return False
    
    def _is_text_column(self, series: pd.Series, column_name: str) -> bool:
        """Check if column contains free-text data."""
        if series.dtype == 'object':
            # Check average string length
            avg_length = series.astype(str).str.len().mean()
            if avg_length > 50:  # Long text suggests free text
                return True
        
        return False
    
    def analyze_numerical_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Perform numerical analysis on a column.
        
        Args:
            column: Pandas Series with numerical data
            column_name: Name of the column
            
        Returns:
            Dictionary with numerical statistics
        """
        try:
            clean_series = pd.to_numeric(column, errors='coerce').dropna()
            
            if len(clean_series) == 0:
                return {"error": "No valid numerical data"}
            
            stats = {
                'type': 'numerical',
                'count': len(clean_series),
                'missing': len(column) - len(clean_series),
                'mean': clean_series.mean(),
                'median': clean_series.median(),
                'std': clean_series.std(),
                'min': clean_series.min(),
                'max': clean_series.max(),
                'q25': clean_series.quantile(0.25),
                'q75': clean_series.quantile(0.75),
                'skewness': clean_series.skew(),
                'kurtosis': clean_series.kurtosis()
            }
            
            # Healthcare-specific insights
            if 'age' in column_name.lower():
                stats['healthcare_insights'] = {
                    'age_groups': {
                        'pediatric': (clean_series < 18).sum(),
                        'adult': ((clean_series >= 18) & (clean_series < 65)).sum(),
                        'elderly': (clean_series >= 65).sum()
                    }
                }
            
            return stats
            
        except Exception as e:
            self._log_operation_error(f"numerical_analysis", column_name, str(e))
            return {"error": f"Numerical analysis failed: {str(e)}"}
    
    def analyze_categorical_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Perform categorical analysis on a column.
        
        Args:
            column: Pandas Series with categorical data
            column_name: Name of the column
            
        Returns:
            Dictionary with categorical statistics
        """
        try:
            clean_series = column.dropna().astype(str)
            
            if len(clean_series) == 0:
                return {"error": "No valid categorical data"}
            
            value_counts = clean_series.value_counts()
            total_count = len(clean_series)
            
            stats = {
                'type': 'categorical',
                'count': total_count,
                'missing': len(column) - total_count,
                'unique_values': len(value_counts),
                'most_common': value_counts.head(10).to_dict(),
                'distribution': (value_counts / total_count * 100).round(2).to_dict()
            }
            
            # Healthcare-specific insights for gender
            if 'gender' in column_name.lower() or 'sex' in column_name.lower():
                stats['healthcare_insights'] = {
                    'gender_distribution': stats['distribution'],
                    'dominant_gender': value_counts.index[0] if len(value_counts) > 0 else None
                }
            
            # Healthcare-specific insights for drugs/medications
            if 'drug' in column_name.lower() or 'medication' in column_name.lower():
                stats['healthcare_insights'] = {
                    'top_medications': dict(value_counts.head(5)),
                    'medication_diversity': len(value_counts)
                }
            
            return stats
            
        except Exception as e:
            self._log_operation_error(f"categorical_analysis", column_name, str(e))
            return {"error": f"Categorical analysis failed: {str(e)}"}
    
    def analyze_datetime_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Perform datetime analysis on a column.
        
        Args:
            column: Pandas Series with datetime data
            column_name: Name of the column
            
        Returns:
            Dictionary with datetime statistics
        """
        try:
            clean_series = pd.to_datetime(column, errors='coerce').dropna()
            
            if len(clean_series) == 0:
                return {"error": "No valid datetime data"}
            
            stats = {
                'type': 'datetime',
                'count': len(clean_series),
                'missing': len(column) - len(clean_series),
                'min_date': clean_series.min(),
                'max_date': clean_series.max(),
                'date_range_days': (clean_series.max() - clean_series.min()).days
            }
            
            # Time-based analysis
            if len(clean_series) > 1:
                stats['time_insights'] = {
                    'yearly_distribution': clean_series.dt.year.value_counts().head(5).to_dict(),
                    'monthly_distribution': clean_series.dt.month.value_counts().head(12).to_dict(),
                    'weekday_distribution': clean_series.dt.dayofweek.value_counts().to_dict()
                }
            
            # Healthcare-specific insights
            if 'birth' in column_name.lower() or 'dob' in column_name.lower():
                current_year = datetime.now().year
                ages = current_year - clean_series.dt.year
                stats['healthcare_insights'] = {
                    'age_statistics': {
                        'mean_age': ages.mean(),
                        'median_age': ages.median(),
                        'age_distribution': {
                            'pediatric': (ages < 18).sum(),
                            'adult': ((ages >= 18) & (ages < 65)).sum(),
                            'elderly': (ages >= 65).sum()
                        }
                    }
                }
            
            return stats
            
        except Exception as e:
            self._log_operation_error(f"datetime_analysis", column_name, str(e))
            return {"error": f"Datetime analysis failed: {str(e)}"}
    
    def analyze_boolean_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Perform boolean analysis on a column.
        
        Args:
            column: Pandas Series with boolean data
            column_name: Name of the column
            
        Returns:
            Dictionary with boolean statistics
        """
        try:
            # Convert to boolean
            clean_series = column.dropna()
            
            # Standardize boolean values
            bool_mapping = {
                'true': True, 'yes': True, 'y': True, '1': True, 't': True,
                'false': False, 'no': False, 'n': False, '0': False, 'f': False
            }
            
            standardized = clean_series.astype(str).str.lower().map(bool_mapping)
            standardized = standardized.dropna()
            
            if len(standardized) == 0:
                return {"error": "No valid boolean data"}
            
            value_counts = standardized.value_counts()
            total_count = len(standardized)
            
            stats = {
                'type': 'boolean',
                'count': total_count,
                'missing': len(column) - total_count,
                'true_count': value_counts.get(True, 0),
                'false_count': value_counts.get(False, 0),
                'true_percentage': (value_counts.get(True, 0) / total_count * 100).round(2),
                'false_percentage': (value_counts.get(False, 0) / total_count * 100).round(2)
            }
            
            return stats
            
        except Exception as e:
            self._log_operation_error(f"boolean_analysis", column_name, str(e))
            return {"error": f"Boolean analysis failed: {str(e)}"}
    
    def analyze_text_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Perform text analysis on a column.
        
        Args:
            column: Pandas Series with text data
            column_name: Name of the column
            
        Returns:
            Dictionary with text statistics
        """
        try:
            clean_series = column.dropna().astype(str)
            
            if len(clean_series) == 0:
                return {"error": "No valid text data"}
            
            stats = {
                'type': 'text',
                'count': len(clean_series),
                'missing': len(column) - len(clean_series),
                'avg_length': clean_series.str.len().mean(),
                'max_length': clean_series.str.len().max(),
                'min_length': clean_series.str.len().min(),
                'empty_strings': (clean_series == '').sum()
            }
            
            return stats
            
        except Exception as e:
            self._log_operation_error(f"text_analysis", column_name, str(e))
            return {"error": f"Text analysis failed: {str(e)}"}
    
    def analyze_column(self, column: pd.Series, column_name: str) -> Dict[str, Any]:
        """
        Main method to analyze a column with appropriate operations.
        
        Args:
            column: Pandas Series to analyze
            column_name: Name of the column
            
        Returns:
            Dictionary with analysis results
        """
        # Detect column type
        column_type = self.detect_column_type(column, column_name)
        
        # Route to appropriate analysis method
        if column_type == ColumnType.NUMERICAL:
            return self.analyze_numerical_column(column, column_name)
        elif column_type == ColumnType.CATEGORICAL:
            return self.analyze_categorical_column(column, column_name)
        elif column_type == ColumnType.DATETIME:
            return self.analyze_datetime_column(column, column_name)
        elif column_type == ColumnType.BOOLEAN:
            return self.analyze_boolean_column(column, column_name)
        elif column_type == ColumnType.TEXT:
            return self.analyze_text_column(column, column_name)
        else:
            return {"error": "Unknown column type", "type": "unknown"}
    
    def analyze_dataframe(self, df: pd.DataFrame) -> Dict[str, Any]:
        """
        Analyze entire dataframe and return structured insights.
        
        Args:
            df: Pandas DataFrame to analyze
            
        Returns:
            Dictionary with comprehensive analysis results
        """
        results = {
            'schema_overview': {
                'total_columns': len(df.columns),
                'total_rows': len(df),
                'column_types': {},
                'type_distribution': {}
            },
            'column_analysis': {},
            'summary_insights': []
        }
        
        # Analyze each column
        for column_name in df.columns:
            column_analysis = self.analyze_column(df[column_name], column_name)
            results['column_analysis'][column_name] = column_analysis
            
            # Track type distribution
            if 'type' in column_analysis and 'error' not in column_analysis:
                col_type = column_analysis['type']
                results['schema_overview']['column_types'][column_name] = col_type
                results['schema_overview']['type_distribution'][col_type] = \
                    results['schema_overview']['type_distribution'].get(col_type, 0) + 1
        
        # Generate summary insights
        results['summary_insights'] = self._generate_summary_insights(results)
        
        return results
    
    def _generate_summary_insights(self, analysis_results: Dict[str, Any]) -> List[str]:
        """Generate summary insights from analysis results."""
        insights = []
        
        # Gender distribution insight
        for col_name, analysis in analysis_results['column_analysis'].items():
            if 'gender' in col_name.lower() and 'healthcare_insights' in analysis:
                gender_dist = analysis['healthcare_insights'].get('gender_distribution', {})
                if gender_dist:
                    dominant = max(gender_dist, key=gender_dist.get)
                    insights.append(f"Gender distribution: {dominant} dominant ({gender_dist[dominant]:.1f}%)")
        
        # Age-related insights
        for col_name, analysis in analysis_results['column_analysis'].items():
            if 'age' in col_name.lower() and 'healthcare_insights' in analysis:
                age_groups = analysis['healthcare_insights'].get('age_groups', {})
                if age_groups:
                    insights.append(f"Age groups: Pediatric ({age_groups.get('pediatric', 0)}), "
                                  f"Adult ({age_groups.get('adult', 0)}), Elderly ({age_groups.get('elderly', 0)})")
        
        # Data quality insights
        total_missing = sum(analysis.get('missing', 0) for analysis in analysis_results['column_analysis'].values())
        total_rows = analysis_results['schema_overview']['total_rows']
        if total_missing > 0:
            missing_percentage = (total_missing / (total_rows * len(analysis_results['column_analysis']))) * 100
            insights.append(f"Data quality: {missing_percentage:.1f}% missing values across all columns")
        
        return insights
    
    def _log_operation_error(self, operation: str, column_name: str, error_message: str):
        """Log operation errors for debugging."""
        error_msg = f"Operation '{operation}' failed on column '{column_name}': {error_message}"
        logger.warning(error_msg)
        self.operation_log.append({
            'timestamp': datetime.now(),
            'operation': operation,
            'column': column_name,
            'error': error_message
        })
    
    def get_operation_log(self) -> List[Dict[str, Any]]:
        """Get the operation log for debugging."""
        return self.operation_log


def create_sample_healthcare_data() -> pd.DataFrame:
    """Create sample healthcare dataset for testing."""
    np.random.seed(42)
    n_records = 1000
    
    data = {
        'patient_id': range(1, n_records + 1),
        'age': np.random.randint(18, 85, n_records),
        'gender': np.random.choice(['Male', 'Female', 'Other'], n_records, p=[0.48, 0.51, 0.01]),
        'diagnosis': np.random.choice(['Hypertension', 'Diabetes', 'Asthma', 'Heart Disease', 'None'], n_records),
        'drug_name': np.random.choice(['Metformin', 'Atorvastatin', 'Lisinopril', 'Albuterol', 'Aspirin'], n_records),
        'dosage': np.random.normal(100, 25, n_records),
        'admission_date': pd.date_range('2023-01-01', periods=n_records, freq='h'),
        'discharge_date': pd.date_range('2023-01-02', periods=n_records, freq='h'),
        'emergency_visit': np.random.choice([True, False], n_records, p=[0.2, 0.8]),
        'insurance_type': np.random.choice(['Private', 'Medicare', 'Medicaid', 'Self-pay'], n_records),
        'doctor_notes': ['Patient presents with ' + np.random.choice(['fever', 'cough', 'pain', 'fatigue']) 
                        for _ in range(n_records)]
    }
    
    df = pd.DataFrame(data)
    
    # Ensure proper data types
    df['patient_id'] = df['patient_id'].astype('int64')
    df['age'] = df['age'].astype('int64')
    df['gender'] = df['gender'].astype('category')
    df['diagnosis'] = df['diagnosis'].astype('category')
    df['drug_name'] = df['drug_name'].astype('category')
    df['dosage'] = df['dosage'].astype('float64')
    df['emergency_visit'] = df['emergency_visit'].astype('bool')
    df['insurance_type'] = df['insurance_type'].astype('category')
    df['doctor_notes'] = df['doctor_notes'].astype('string')
    
    return df


# Example usage and testing
if __name__ == "__main__":
    # Create sample data
    sample_df = create_sample_healthcare_data()
    
    # Initialize analyzer
    analyzer = SchemaAnalyzer()
    
    # Analyze the dataframe
    results = analyzer.analyze_dataframe(sample_df)
    
    # Print results
    print("=" * 80)
    print("HEALTHCARE DATA ANALYSIS RESULTS")
    print("=" * 80)
    
    print("\nSCHEMA OVERVIEW:")
    print(f"Total columns: {results['schema_overview']['total_columns']}")
    print(f"Total rows: {results['schema_overview']['total_rows']}")
    print(f"Type distribution: {results['schema_overview']['type_distribution']}")
    
    print("\nCOLUMN ANALYSIS:")
    for col_name, analysis in results['column_analysis'].items():
        print(f"\n{col_name.upper()} ({analysis.get('type', 'unknown')}):")
        if 'error' in analysis:
            print(f"  Error: {analysis['error']}")
        else:
            if analysis['type'] == 'categorical':
                print(f"  Distribution: {analysis.get('distribution', {})}")
            elif analysis['type'] == 'numerical':
                print(f"  Mean: {analysis.get('mean', 'N/A'):.2f}, Std: {analysis.get('std', 'N/A'):.2f}")
            elif analysis['type'] == 'datetime':
                print(f"  Range: {analysis.get('min_date', 'N/A')} to {analysis.get('max_date', 'N/A')}")
            elif analysis['type'] == 'boolean':
                print(f"  True: {analysis.get('true_percentage', 'N/A')}%, False: {analysis.get('false_percentage', 'N/A')}%")
    
    print("\nSUMMARY INSIGHTS:")
    for insight in results['summary_insights']:
        print(f"  • {insight}")



# ==================================================
# From: dataset_profiler.py
# ==================================================

"""
Dataset Profiler Module
Inspects arbitrary datasets, detects types, statistics, distributions, and quality metrics.
Does NOT assume any fixed column names.
"""

import io
import uuid
import numpy as np
import pandas as pd
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime


class DatasetProfiler:
    """
    Intelligent Profiler for arbitrary tabular datasets (CSV, Excel, Parquet).
    Generates comprehensive column-level statistics, distributions, and data quality metrics.
    """

    def __init__(self):
        self.raw_data_store: Dict[str, pd.DataFrame] = {}

    def ingest_dataset(self, file_source, filename: str) -> Tuple[str, pd.DataFrame, Dict[str, Any]]:
        """
        Ingests a tabular dataset, assigns a dataset ID, stores working copy,
        and generates immediate initial profile.
        """
        from typing import Tuple
        dataset_id = str(uuid.uuid4())
        
        # Load dataset
        if isinstance(file_source, str):
            if file_source.lower().endswith(('.xlsx', '.xls')):
                df = pd.read_excel(file_source)
            else:
                df = pd.read_csv(file_source)
        elif hasattr(file_source, "read"):
            if hasattr(file_source, "seek"):
                file_source.seek(0)
            if filename.lower().endswith(('.xlsx', '.xls')):
                df = pd.read_excel(file_source)
            else:
                try:
                    df = pd.read_csv(file_source)
                except Exception:
                    if hasattr(file_source, "seek"):
                        file_source.seek(0)
                    df = pd.read_csv(file_source, encoding="latin1")
        else:
            raise ValueError("Unsupported file source format.")

        # Save isolated working copy
        self.raw_data_store[dataset_id] = df.copy()
        
        profile = self.profile_dataframe(df, filename=filename)
        profile["dataset_id"] = dataset_id
        
        return dataset_id, df, profile

    def get_dataset(self, dataset_id: str) -> Optional[pd.DataFrame]:
        return self.raw_data_store.get(dataset_id)

    def profile_dataframe(self, df: pd.DataFrame, filename: str = "dataset") -> Dict[str, Any]:
        """
        Profiles the entire dataframe with deep statistical and type inspection.
        """
        n_rows, n_cols = df.shape
        columns_profile = {}
        
        total_missing = int(df.isna().sum().sum())
        total_cells = max(n_rows * n_cols, 1)
        missing_rate = round((total_missing / total_cells) * 100, 2)
        duplicate_rows = int(df.duplicated().sum())

        for col in df.columns:
            series = df[col]
            col_info = self._profile_column(series, col, n_rows)
            columns_profile[col] = col_info

        # Calculate overall dataset health score (0-100)
        quality_penalties = 0
        if missing_rate > 20:
            quality_penalties += min(30, int(missing_rate))
        if duplicate_rows > 0:
            quality_penalties += min(20, int((duplicate_rows / max(n_rows, 1)) * 100))
        
        data_quality_score = max(10, 100 - quality_penalties)

        return {
            "filename": filename,
            "row_count": n_rows,
            "column_count": n_cols,
            "total_missing_cells": total_missing,
            "missing_rate_pct": missing_rate,
            "duplicate_row_count": duplicate_rows,
            "data_quality_score": data_quality_score,
            "columns": columns_profile,
            "sample_records": df.head(5).replace({np.nan: None}).to_dict(orient="records"),
        }

    def _profile_column(self, series: pd.Series, col_name: str, total_rows: int) -> Dict[str, Any]:
        clean = series.dropna()
        missing_count = int(series.isna().sum())
        unique_count = int(series.nunique(dropna=True))
        cardinality_ratio = round(unique_count / max(total_rows, 1), 4)
        
        detected_type = "unknown"
        is_date = False
        is_numeric = False
        stats = {}
        top_categories = []

        # 1. Date check
        if pd.api.types.is_datetime64_any_dtype(series):
            detected_type = "datetime"
            is_date = True
        elif clean.dtype == object or clean.dtype == "string":
            # Attempt date parsing on sample
            sample_clean = clean.head(50).astype(str)
            date_matches = 0
            for val in sample_clean:
                if len(val.strip()) >= 6:
                    try:
                        pd.to_datetime(val)
                        date_matches += 1
                    except (ValueError, TypeError):
                        pass
            if len(sample_clean) > 0 and (date_matches / len(sample_clean)) > 0.7:
                detected_type = "datetime"
                is_date = True

        # 2. Numeric check
        if not is_date:
            if pd.api.types.is_numeric_dtype(series):
                detected_type = "numeric"
                is_numeric = True
            else:
                # Test numeric conversion
                numeric_conv = pd.to_numeric(clean, errors="coerce")
                if clean.shape[0] > 0 and (numeric_conv.notna().sum() / clean.shape[0]) > 0.8:
                    detected_type = "numeric"
                    is_numeric = True
                    clean = numeric_conv.dropna()

        # 3. Categorical / Boolean / Text check
        if not is_date and not is_numeric:
            if unique_count == 2 or clean.dtype == bool:
                detected_type = "boolean"
            elif cardinality_ratio < 0.2 or unique_count < 50:
                detected_type = "categorical"
            else:
                avg_len = clean.astype(str).str.len().mean() if len(clean) > 0 else 0
                detected_type = "text" if avg_len > 25 else "categorical"

        # Compute specific statistics
        if is_numeric and len(clean) > 0:
            num_clean = pd.to_numeric(clean, errors="coerce").dropna()
            if len(num_clean) > 0:
                stats = {
                    "min": float(num_clean.min()),
                    "max": float(num_clean.max()),
                    "mean": float(round(num_clean.mean(), 2)),
                    "std": float(round(num_clean.std(), 2)) if len(num_clean) > 1 else 0.0,
                    "median": float(round(num_clean.median(), 2)),
                    "q25": float(round(num_clean.quantile(0.25), 2)),
                    "q75": float(round(num_clean.quantile(0.75), 2)),
                }
        
        if detected_type in ["categorical", "boolean", "text"]:
            val_counts = series.value_counts(dropna=True).head(5)
            top_categories = [{"value": str(k), "count": int(v)} for k, v in val_counts.items()]

        sample_vals = [str(x) for x in series.dropna().head(5).tolist()]

        return {
            "name": col_name,
            "detected_type": detected_type,
            "pandas_dtype": str(series.dtype),
            "missing_count": missing_count,
            "missing_pct": round((missing_count / max(total_rows, 1)) * 100, 2),
            "unique_count": unique_count,
            "cardinality_ratio": cardinality_ratio,
            "is_date": is_date,
            "is_numeric": is_numeric,
            "sample_values": sample_vals,
            "statistics": stats,
            "top_categories": top_categories
        }



# ==================================================
# From: semantic_mapper.py
# ==================================================

"""
Semantic Schema Mapper Module (3-Layer Architecture)
Maps arbitrary source columns to Canonical Concepts:
DRUG, DATE, PATIENT_ID, DIAGNOSIS, AGE, GENDER, DOSAGE, REGION, QUANTITY, PRESCRIBER, RISK_SCORE.
"""

import re
import json
import pandas as pd
import numpy as np
from typing import Dict, Any, List, Optional, Tuple


CANONICAL_FIELDS = {
    "DRUG": {
        "description": "Pharmaceutical product, medication, drug name, or compound",
        "keywords": ["drug", "drug_name", "medication", "medicine", "compound", "brand_name", "generic_name", "rx_name", "product_name", "pharmaceutical", "agent"],
    },
    "DATE": {
        "description": "Prescription, transaction, admission, or dispensing date/timestamp",
        "keywords": ["date", "rx_date", "prescribed_on", "dispensed_date", "admission_date", "visit_date", "timestamp", "datetime", "created_at", "order_date", "trans_date"],
    },
    "PATIENT_ID": {
        "description": "Unique identifier for patient, subject, or customer",
        "keywords": ["patient_id", "patient_no", "subject_id", "pat_id", "member_id", "client_id", "mrn", "patient_code", "user_id", "customer_id"],
    },
    "DIAGNOSIS": {
        "description": "Clinical diagnosis, indication, pathology, or ICD condition",
        "keywords": ["diagnosis", "condition", "disease", "indication", "icd", "icd10", "icd9", "problem", "symptom", "clinical_condition", "disorder"],
    },
    "AGE": {
        "description": "Patient age in years (numerical)",
        "keywords": ["age", "patient_age", "pat_age", "years_old", "age_years", "dob_years"],
    },
    "GENDER": {
        "description": "Patient biological sex or gender identity",
        "keywords": ["gender", "sex", "patient_gender", "pat_sex", "biological_sex"],
    },
    "DOSAGE": {
        "description": "Strength or dosage specification (e.g. 500mg, 10ml, 5mg/day)",
        "keywords": ["dosage", "dose", "strength", "dose_mg", "potency", "concentration", "dose_amount"],
    },
    "REGION": {
        "description": "Geographical location, territory, clinic state, or hospital region",
        "keywords": ["region", "location", "area", "state", "city", "territory", "hospital_site", "zone", "province", "country"],
    },
    "QUANTITY": {
        "description": "Number of units, count, tablets dispensed, or volume",
        "keywords": ["quantity", "count", "units", "dispensed_qty", "qty", "tablets_count", "amount_dispensed", "package_size", "volume"],
    },
    "PRESCRIBER": {
        "description": "Prescribing physician, doctor, clinic provider, or clinician ID",
        "keywords": ["prescriber", "physician", "doctor", "provider", "dr_name", "clinician", "specialist", "prescriber_id", "doctor_id", "npi"],
    },
    "RISK_SCORE": {
        "description": "Clinical risk metric, risk tier, severity score, or target label",
        "keywords": ["risk_score", "risk", "severity", "risk_label", "target", "adverse_event", "readmitted", "high_risk", "toxicity_score"],
    },
    "MENOPAUSE_STATUS": {
        "description": "Menopause status or menopausal state",
        "keywords": ["meno", "menopause", "menopausal"],
    },
    "TUMOR_GRADE": {
        "description": "Tumor or disease grade",
        "keywords": ["grade", "tumor_grade", "tumour_grade"],
    },
    "LYMPH_NODE_COUNT": {
        "description": "Number of involved or examined lymph nodes",
        "keywords": ["nodes", "lymph_nodes", "node_count", "positive_nodes"],
    },
    "PROGESTERONE_RECEPTOR": {
        "description": "Progesterone receptor status or measurement",
        "keywords": ["pgr", "progesterone_receptor", "pr_status"],
    },
    "HORMONE_THERAPY": {
        "description": "Hormone therapy treatment indicator",
        "keywords": ["hormon", "hormone", "hormonal", "hormone_therapy"],
    },
    "RELAPSE_FREE_SURVIVAL_TIME": {
        "description": "Time until relapse or relapse-free survival duration",
        "keywords": ["rfstime", "rfs_time", "relapse_free_survival", "relapse_time"],
    }
}


class SemanticMapper:
    """
    3-Layer Canonical Schema Mapper.
    Uses Name Matching (Layer 1) -> Content Heuristics (Layer 2) -> LLM Assistance (Layer 3).
    """

    def __init__(self, meaning_agent=None):
        if meaning_agent is None:
            from utils.column_meaning_agent import ColumnMeaningAgent
            meaning_agent = ColumnMeaningAgent()
        self.meaning_agent = meaning_agent

    def map_columns(self, df: pd.DataFrame, columns_profile: Dict[str, Any], use_llm: bool = True) -> Dict[str, Any]:
        """
        Maps all columns in the dataset to canonical semantic concepts.
        Returns:
            canonical_mapping: {source_col: canonical_field or 'OTHER'}
            mapping_evidence: {source_col: {canonical, confidence, layer, evidence}}
        """
        canonical_mapping = {}
        mapping_details = {}

        unmapped_cols = []

        for col_name, prof in columns_profile.items():
            series = df[col_name] if col_name in df.columns else pd.Series(dtype=object)
            
            # --- Layer 1: Rule & Fuzzy Name Matching ---
            l1_field, l1_conf, l1_ev = self._layer1_name_matching(col_name)
            if l1_conf >= 0.85:
                canonical_mapping[col_name] = l1_field
                mapping_details[col_name] = {
                    "canonical": l1_field,
                    "confidence": l1_conf,
                    "layer": "Layer 1 (Name Rule & Similarity)",
                    "evidence": l1_ev
                }
                continue

            # --- Layer 2: Content & Data Type Heuristics ---
            l2_field, l2_conf, l2_ev = self._layer2_content_heuristics(col_name, series, prof)
            if l2_conf >= 0.70:
                canonical_mapping[col_name] = l2_field
                mapping_details[col_name] = {
                    "canonical": l2_field,
                    "confidence": l2_conf,
                    "layer": "Layer 2 (Content & Distribution Heuristics)",
                    "evidence": l2_ev
                }
                continue

            # If L1 had weak suggestion, combine with L2
            if l1_field and l1_conf >= 0.5:
                canonical_mapping[col_name] = l1_field
                mapping_details[col_name] = {
                    "canonical": l1_field,
                    "confidence": l1_conf,
                    "layer": "Layer 1 (Partial Match)",
                    "evidence": l1_ev
                }
            else:
                learned = self.meaning_agent.resolve(col_name, prof)
                if learned and learned.get("canonical") != "OTHER":
                    canonical_mapping[col_name] = learned["canonical"]
                    mapping_details[col_name] = {
                        "canonical": learned["canonical"],
                        "confidence": learned["confidence"],
                        "layer": "Learned Column Meaning Agent",
                        "evidence": learned.get("meaning", "Learned from prior feedback or online evidence."),
                        "usage": learned.get("usage", ""),
                    }
                else:
                    unmapped_cols.append((col_name, prof))

        # --- Layer 3: LLM Assistance for Ambiguous Columns ---
        if unmapped_cols:
            if use_llm:
                l3_results = self._layer3_llm_inference(unmapped_cols, df)
                for col_name, (can_field, conf, ev) in l3_results.items():
                    canonical_mapping[col_name] = can_field
                    mapping_details[col_name] = {
                        "canonical": can_field,
                        "confidence": conf,
                        "layer": "Layer 3 (LLM Semantic Reasoning)",
                        "evidence": ev
                    }
            else:
                for col_name, _ in unmapped_cols:
                    canonical_mapping[col_name] = "OTHER"
                    mapping_details[col_name] = {
                        "canonical": "OTHER",
                        "confidence": 0.3,
                        "layer": "Fallback",
                        "evidence": "No clear semantic match found."
                    }

        return {
            "canonical_mapping": canonical_mapping,
            "mapping_details": mapping_details,
            "mapped_canonical_fields": [v for v in canonical_mapping.values() if v != "OTHER"]
        }

    def _layer1_name_matching(self, col_name: str) -> Tuple[Optional[str], float, str]:
        """Name normalization and token fuzzy matching."""
        clean_name = re.sub(r"[^a-zA-Z0-9]", "_", col_name.lower()).strip("_")
        tokens = set(clean_name.split("_"))

        best_field = None
        best_score = 0.0
        best_reason = ""

        for canon_name, info in CANONICAL_FIELDS.items():
            for kw in info["keywords"]:
                kw_clean = kw.lower()
                if clean_name == kw_clean:
                    return canon_name, 0.98, f"Exact column name match '{col_name}' == '{kw}'"
                
                # Substring or token overlap
                if kw_clean in clean_name or clean_name in kw_clean:
                    score = 0.88
                    if score > best_score:
                        best_score = score
                        best_field = canon_name
                        best_reason = f"Column name '{col_name}' contains canonical keyword '{kw}'"

                kw_tokens = set(kw_clean.split("_"))
                overlap = tokens.intersection(kw_tokens)
                if overlap:
                    score = 0.75 + (len(overlap) * 0.05)
                    if score > best_score:
                        best_score = min(score, 0.92)
                        best_field = canon_name
                        best_reason = f"Tokens {list(overlap)} match canonical keyword '{kw}'"

        return best_field, best_score, best_reason

    def _layer2_content_heuristics(self, col_name: str, series: pd.Series, prof: Dict[str, Any]) -> Tuple[Optional[str], float, str]:
        """Data-type and value distribution heuristics."""
        clean = series.dropna()
        if len(clean) == 0:
            return None, 0.0, "Empty series"

        is_numeric = prof.get("is_numeric", False)
        is_date = prof.get("is_date", False)
        unique_cnt = prof.get("unique_count", len(clean))
        total_len = max(len(series), 1)

        # 1. Date Check
        if is_date:
            return "DATE", 0.90, "Column values parse as valid timestamps/dates"

        # 2. Gender Check
        if not is_numeric and unique_cnt in [2, 3, 4]:
            val_strs = set(clean.astype(str).str.strip().str.lower().unique())
            if val_strs.issubset({"m", "f", "male", "female", "other", "unknown", "u", "1", "0"}):
                if any(x in val_strs for x in ["m", "f", "male", "female"]):
                    return "GENDER", 0.95, f"Values match biological sex domain: {list(val_strs)}"

        # 3. Age Check
        if is_numeric:
            stats = prof.get("statistics", {})
            min_val = stats.get("min", 0)
            max_val = stats.get("max", 0)
            if 0 <= min_val <= 120 and 0 < max_val <= 120:
                normalized_name = re.sub(r"[^a-z0-9]", "_", col_name.lower())
                age_tokens = set(normalized_name.split("_"))
                if age_tokens.intersection({"age", "ages", "year", "years", "yr", "yrs"}):
                    return "AGE", 0.85, f"Numeric values in biological human age range [{min_val}, {max_val}]"

        # 4. Patient Identifier
        if (unique_cnt / total_len) > 0.6:
            # Check pattern like P1234, ID-9988, 10001
            sample = clean.head(10).astype(str).tolist()
            if any(re.match(r"^[A-Za-z0-9_-]{3,20}$", str(s)) for s in sample):
                if any(k in col_name.lower() for k in ["id", "no", "code", "num", "key", "subject"]):
                    return "PATIENT_ID", 0.88, f"High cardinality ({unique_cnt}/{total_len}) and ID-like formatting"

        # 5. Dosage patterns
        if not is_numeric:
            sample_str = clean.head(20).astype(str).str.lower()
            dose_matches = sample_str.apply(lambda x: bool(re.search(r"\d+\s*(mg|mcg|g|ml|iu|tablets?|caps?|units?)", x))).sum()
            if dose_matches > 5:
                return "DOSAGE", 0.92, f"Values contain dosage unit metrics (e.g. mg, ml, tab)"

        # 6. Quantity check
        if is_numeric:
            stats = prof.get("statistics", {})
            min_val = stats.get("min", 0)
            max_val = stats.get("max", 0)
            if min_val >= 0 and max_val <= 5000:
                if any(k in col_name.lower() for k in ["qty", "count", "num", "total", "amount", "units", "disp"]):
                    return "QUANTITY", 0.85, f"Numeric distribution consistent with dispensing counts [{min_val}, {max_val}]"

        # 7. Diagnosis check
        if not is_numeric:
            sample_str = clean.head(20).astype(str).str.lower()
            diag_kw = ["diabetes", "hypertension", "infection", "cancer", "pain", "asthma", "copd", "failure", "syndrome", "fever", "icd"]
            diag_matches = sample_str.apply(lambda x: any(dk in x for dk in diag_kw)).sum()
            if diag_matches > 3:
                return "DIAGNOSIS", 0.89, f"Text values contain medical diagnostic terminology"

        return None, 0.0, "Heuristics inconclusive"

    def _layer3_llm_inference(self, unmapped: List[Tuple[str, Dict[str, Any]]], df: pd.DataFrame) -> Dict[str, Tuple[str, float, str]]:
        """Invokes LLM for difficult semantic inference."""
        from utils.llm_core import query_llm
        
        results = {}
        items_payload = []
        for col_name, prof in unmapped:
            items_payload.append({
                "column_name": col_name,
                "dtype": prof.get("pandas_dtype", ""),
                "sample_values": prof.get("sample_values", [])[:5]
            })

        system = (
            "You are a Clinical Healthcare Schema Mapper. Map each given column to one of these exact canonical concepts: "
            "[DRUG, DATE, PATIENT_ID, DIAGNOSIS, AGE, GENDER, DOSAGE, REGION, QUANTITY, PRESCRIBER, RISK_SCORE, OTHER]. "
            "Return JSON object: { \"col_name\": {\"canonical\": \"CONCEPT\", \"reason\": \"short reason\"} }"
        )
        prompt = f"Map these healthcare dataset columns to canonical concepts:\n{json.dumps(items_payload, indent=2)}"

        try:
            raw_res = query_llm(prompt, system=system, temperature=0.1)
            start = raw_res.find("{")
            end = raw_res.rfind("}") + 1
            parsed = json.loads(raw_res[start:end])
            
            for col_name, _ in unmapped:
                if col_name in parsed and isinstance(parsed[col_name], dict):
                    can = parsed[col_name].get("canonical", "OTHER").upper()
                    if can not in CANONICAL_FIELDS and can != "OTHER":
                        can = "OTHER"
                    reason = parsed[col_name].get("reason", "Inferred by LLM reasoning")
                    results[col_name] = (can, 0.80 if can != "OTHER" else 0.40, reason)
                else:
                    results[col_name] = ("OTHER", 0.3, "Unrecognized field")
        except Exception:
            for col_name, _ in unmapped:
                results[col_name] = ("OTHER", 0.3, "Fallback classification")

        return results


