# Combined module: media_utils.py
# This file was automatically generated by combining multiple smaller utilities.


# ==================================================
# From: image_utils.py
# ==================================================

import io
import os
import platform
import shutil
from pathlib import Path

try:
    from PIL import Image, ImageFile
    ImageFile.LOAD_TRUNCATED_IMAGES = True
except Exception:
    Image = None
    ImageFile = None

try:
    import fitz
except ImportError:
    fitz = None

import plotly.express as px
import plotly.graph_objects as go
import tempfile
import pandas as pd
import numpy as np


def is_image_file(filename: str) -> bool:
    if not isinstance(filename, str):
        filename = getattr(filename, "name", str(filename))
    return filename.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"))


def is_pdf_file(filename: str) -> bool:
    if not isinstance(filename, str):
        filename = getattr(filename, "name", str(filename))
    return filename.lower().endswith(".pdf")


def load_image_from_bytes(uploaded_file) -> "Image.Image":
    """
    Loads an image into a PIL Image object with multiple fallback decoding strategies:
    1. Pillow (Image.open)
    2. OpenCV (cv2.imdecode)
    3. PyMuPDF (fitz)
    """
    data = None
    if isinstance(uploaded_file, (str, Path)):
        with open(str(uploaded_file), "rb") as f:
            data = f.read()
    elif hasattr(uploaded_file, "read"):
        if hasattr(uploaded_file, "seek"):
            uploaded_file.seek(0)
        data = uploaded_file.read()
    elif isinstance(uploaded_file, (bytes, bytearray)):
        data = bytes(uploaded_file)
    else:
        raise ValueError(f"Unsupported input type for image loading: {type(uploaded_file)}")

    if not data:
        raise ValueError("Provided image data is empty.")

    # Strategy 1: Standard PIL Image.open
    if Image is not None:
        try:
            img = Image.open(io.BytesIO(data))
            img.load()
            return img.convert("RGB")
        except Exception:
            pass

    # Strategy 2: OpenCV decoding fallback
    try:
        import cv2
        import numpy as np
        np_arr = np.frombuffer(data, np.uint8)
        img_mat = cv2.imdecode(np_arr, cv2.IMREAD_COLOR)
        if img_mat is not None:
            img_rgb = cv2.cvtColor(img_mat, cv2.COLOR_BGR2RGB)
            if Image is not None:
                return Image.fromarray(img_rgb)
    except Exception:
        pass

    # Strategy 3: PyMuPDF (fitz) pixmap decoding fallback
    if fitz is not None and Image is not None:
        try:
            doc = fitz.open(stream=data, filetype="image")
            page = doc[0]
            pix = page.get_pixmap(dpi=150)
            img_data = pix.tobytes("png")
            doc.close()
            img = Image.open(io.BytesIO(img_data))
            img.load()
            return img.convert("RGB")
        except Exception:
            pass

    raise RuntimeError("Failed to decode image data using PIL, OpenCV, or PyMuPDF.")


def _extract_with_winocr(image) -> str:
    """
    Extracts text using Windows 10/11 native OCR engine (Windows.Media.Ocr via winocr).
    Thread-safe and asyncio-safe (runs in isolated ThreadPoolExecutor to support Streamlit runtime).
    """
    if platform.system() != "Windows":
        return ""
    try:
        import winocr
        import concurrent.futures
        
        # Preprocessing: ensure within Windows OCR dimension limits (40 <= dim <= 2600)
        img = image.copy()
        max_dim = max(img.width, img.height)
        min_dim = min(img.width, img.height)
        
        if max_dim > 2400:
            scale = 2400.0 / max_dim
            new_size = (int(img.width * scale), int(img.height * scale))
            img = img.resize(new_size, Image.LANCZOS if hasattr(Image, "LANCZOS") else Image.Resampling.LANCZOS)
        elif min_dim < 60:
            scale = 120.0 / max(min_dim, 1)
            new_size = (int(img.width * scale), int(img.height * scale))
            img = img.resize(new_size, Image.BICUBIC if hasattr(Image, "BICUBIC") else Image.Resampling.BICUBIC)
        
        # Streamlit scripts run inside asyncio event loops; isolate sync call in a separate thread
        def _run_sync():
            return winocr.recognize_pil_sync(img)

        with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(_run_sync)
            res = future.result(timeout=20)

        if isinstance(res, dict):
            # Prefer extracted lines for preserving formatting/line breaks
            lines = res.get("lines", [])
            if lines:
                text_lines = [line.get("text", "") for line in lines if isinstance(line, dict)]
                combined = "\n".join(filter(None, text_lines)).strip()
                if combined:
                    return combined
            text = res.get("text", "")
            if text:
                return text.strip()
    except Exception:
        pass
    return ""


def _find_tesseract_binary() -> str:
    """Finds tesseract.exe path on Windows or POSIX systems."""
    which_path = shutil.which("tesseract")
    if which_path:
        return which_path
    
    if platform.system() == "Windows":
        common_paths = [
            r"C:\Program Files\Tesseract-OCR\tesseract.exe",
            r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe",
            os.path.join(os.environ.get("LOCALAPPDATA", ""), r"Programs\Tesseract-OCR\tesseract.exe"),
            os.path.join(os.environ.get("LOCALAPPDATA", ""), r"Tesseract-OCR\tesseract.exe"),
            os.path.join(os.environ.get("USERPROFILE", ""), r"AppData\Local\Programs\Tesseract-OCR\tesseract.exe"),
            os.path.join(os.environ.get("USERPROFILE", ""), r"AppData\Local\Tesseract-OCR\tesseract.exe"),
        ]
        for path in common_paths:
            if path and os.path.exists(path):
                return path
    return ""


def _extract_with_tesseract(image) -> str:
    """Extracts text using pytesseract with automatic binary path discovery."""
    try:
        import pytesseract
    except ImportError:
        return ""

    tess_path = _find_tesseract_binary()
    if tess_path:
        pytesseract.pytesseract.tesseract_cmd = tess_path
        tessdata_dir = os.path.join(os.path.dirname(tess_path), "tessdata")
        if os.path.isdir(tessdata_dir) and "TESSDATA_PREFIX" not in os.environ:
            os.environ["TESSDATA_PREFIX"] = tessdata_dir

    try:
        text = pytesseract.image_to_string(image)
        return text.strip()
    except Exception:
        return ""


def _extract_with_easyocr(image) -> str:
    """Extracts text using easyocr as deep-learning fallback."""
    try:
        import easyocr
        import numpy as np
        reader = easyocr.Reader(["en"], gpu=False, verbose=False)
        img_np = np.array(image)
        results = reader.readtext(img_np, detail=0)
        return "\n".join(results).strip()
    except Exception:
        return ""


def extract_text_from_image(image) -> str:
    """
    Extracts text from a PIL Image using a multi-engine fallback strategy:
    1. Windows Native OCR (winocr) - Instant, zero setup on Windows
    2. Tesseract OCR (pytesseract) - Standard open-source OCR
    3. EasyOCR - Deep-learning based fallback
    """
    if image is None:
        return "[Error] Invalid image provided."

    # Engine 1: Windows Built-in OCR (Fastest and zero-dependency on Windows)
    text = _extract_with_winocr(image)
    if text:
        return text

    # Engine 2: Tesseract OCR (if installed/found)
    text = _extract_with_tesseract(image)
    if text:
        return text

    # Engine 3: EasyOCR (PyTorch-based fallback)
    text = _extract_with_easyocr(image)
    if text:
        return text

    return "[Warning] No text could be detected or extracted from the image. Please ensure the image is clear and contains readable text."


def extract_text_from_pdf(uploaded_file) -> str:
    if fitz is None:
        return "[Error] PyMuPDF (fitz) is not installed. PDF processing is unavailable."
    
    doc = None
    try:
        if isinstance(uploaded_file, (str, Path)):
            doc = fitz.open(str(uploaded_file))
        elif hasattr(uploaded_file, "read"):
            if hasattr(uploaded_file, "seek"):
                uploaded_file.seek(0)
            pdf_stream = io.BytesIO(uploaded_file.read())
            doc = fitz.open(stream=pdf_stream, filetype="pdf")
        else:
            return "[Error] Unsupported PDF input format."
        
        all_text = []
        is_scanned = True
        
        # First pass: try to extract direct digital text
        for page in doc:
            page_text = page.get_text().strip()
            if page_text:
                all_text.append(page_text)
                if len(page_text) > 50:
                    is_scanned = False
        
        extracted_text = "\n\n".join(all_text).strip()
        
        # If sufficient digital text found, return directly
        if extracted_text and not is_scanned:
            return extracted_text

        # Second pass (Scanned PDF): Perform OCR on rendered pages
        ocr_text_parts = []
        if Image is not None:
            for i in range(len(doc)):
                page = doc[i]
                pix = page.get_pixmap(dpi=300)
                img_data = pix.tobytes("png")
                img = Image.open(io.BytesIO(img_data)).convert("RGB")
                
                page_ocr = extract_text_from_image(img)
                if page_ocr and not page_ocr.startswith("[Error]") and not page_ocr.startswith("[Warning]"):
                    ocr_text_parts.append(page_ocr)
        
        final_ocr_text = "\n\n".join(ocr_text_parts).strip()
        
        if final_ocr_text and len(final_ocr_text) > len(extracted_text):
            return final_ocr_text
        if extracted_text:
            return extracted_text
            
        return "[Warning] No text could be extracted. The PDF might be blank or unreadable."
        
    except Exception as e:
        return f"[Error] Failed to extract text from PDF: {str(e)}"
    finally:
        if doc is not None:
            doc.close()


def extract_text_from_file(uploaded_file) -> str:
    """
    Extracts text from either an image or a PDF file.
    Supports both file paths (str/Path) and file-like objects (BytesIO / Streamlit UploadedFile).
    """
    filename = getattr(uploaded_file, "name", str(uploaded_file))
    
    if is_pdf_file(filename):
        return extract_text_from_pdf(uploaded_file)
    
    try:
        image = load_image_from_bytes(uploaded_file)
        return extract_text_from_image(image)
    except Exception as e:
        return f"[Error] Failed to load image: {str(e)}"



# ==================================================
# From: pdf_generator.py
# ==================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from scipy import stats
import io
import base64
from datetime import datetime
import plotly.graph_objects as go
import plotly.express as px


def calculate_cohens_d(group1, group2):
    """Calculate Cohen's d effect size."""
    n1, n2 = len(group1), len(group2)
    mean1, mean2 = np.mean(group1), np.mean(group2)
    var1, var2 = np.var(group1, ddof=1), np.var(group2, ddof=1)
    
    pooled_se = np.sqrt(((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2))
    d = (mean1 - mean2) / pooled_se
    
    return d


def perform_statistical_validation(df, col_map, results):
    """Perform statistical validation tests."""
    validation_results = {}
    
    if results is None:
        return validation_results
    
    # Get numeric columns for statistical tests
    numeric_cols = []
    if col_map is not None:
        for col, cat in col_map.items():
            if cat not in ["patient_id", "date"] and col in df.columns:
                if pd.api.types.is_numeric_dtype(df[col]):
                    numeric_cols.append(col)
    
    if len(numeric_cols) < 2:
        validation_results["error"] = "Insufficient numeric columns for statistical validation"
        return validation_results
    
    # T-test between high and low risk groups (if risk analysis was done)
    if results.get("risk") and results["risk"].get("risk_df") is not None:
        risk_df = results["risk"]["risk_df"]
        if "risk_label" in risk_df.columns:
            high_risk = risk_df[risk_df["risk_label"] == "High Risk"]
            low_risk = risk_df[risk_df["risk_label"] == "Low Risk"]
        elif "__risk_label" in risk_df.columns:
            high_risk = risk_df[risk_df["__risk_label"] == "High Risk"]
            low_risk = risk_df[risk_df["__risk_label"] == "Low Risk"]
        else:
            # Create risk groups based on probability if labels don't exist
            risk_scores = pd.to_numeric(risk_df.get("risk_probability", risk_df.get("risk_score", 0)), errors='coerce')
            median_score = risk_scores.median()
            high_risk = risk_df[risk_scores > median_score]
            low_risk = risk_df[risk_scores <= median_score]
        
        t_test_results = {}
        for col in numeric_cols[:3]:  # Test top 3 numeric columns
            if col in high_risk.columns and col in low_risk.columns:
                try:
                    high_vals = pd.to_numeric(high_risk[col], errors='coerce').dropna()
                    low_vals = pd.to_numeric(low_risk[col], errors='coerce').dropna()
                    
                    if len(high_vals) > 1 and len(low_vals) > 1:
                        t_stat, p_value = stats.ttest_ind(high_vals, low_vals)
                        cohens_d = calculate_cohens_d(high_vals, low_vals)
                        
                        t_test_results[col] = {
                            "t_statistic": t_stat,
                            "p_value": p_value,
                            "cohens_d": cohens_d,
                            "significant": p_value < 0.05
                        }
                except Exception as e:
                    t_test_results[col] = {"error": str(e)}
        
        validation_results["t_test"] = t_test_results
    
    # ANOVA test between cohorts (if cohort analysis was done)
    if results.get("cohort") and results["cohort"].get("cohort_df") is not None:
        cohort_df = results["cohort"]["cohort_df"]
        
        cohort_col = "cohort_label" if "cohort_label" in cohort_df.columns else "__cohort" if "__cohort" in cohort_df.columns else None
        
        if cohort_col:
            cohort_groups = cohort_df[cohort_col].unique()
            
            anova_results = {}
            for col in numeric_cols[:2]:  # Test top 2 numeric columns
                if col in cohort_df.columns:
                    try:
                        group_data = []
                        for cohort in cohort_groups:
                            cohort_data = cohort_df[cohort_df[cohort_col] == cohort]
                            numeric_data = pd.to_numeric(cohort_data[col], errors='coerce').dropna()
                            if len(numeric_data) > 1:
                                group_data.append(numeric_data)
                        
                        if len(group_data) >= 2:
                            f_stat, p_value = stats.f_oneway(*group_data)
                            anova_results[col] = {
                                "f_statistic": f_stat,
                                "p_value": p_value,
                                "significant": p_value < 0.05
                            }
                    except Exception as e:
                        anova_results[col] = {"error": str(e)}
            
            validation_results["anova"] = anova_results
    
    return validation_results


def plotly_to_image(fig):
    """Convert Plotly figure to image for PDF."""
    img_bytes = fig.to_image(format="png", width=800, height=600)
    return img_bytes


def create_dataset_table(df, col_map):
    """Create Table 1: Dataset details."""
    data = []
    
    # Basic dataset info
    data.append(["Dataset Overview", "", ""])
    data.append(["Total Records", f"{len(df):,}", ""])
    data.append(["Total Columns", f"{len(df.columns)}", ""])
    data.append(["Missing Values", f"{df.isna().sum().sum():,}", ""])
    
    # Column analysis
    drug_col, patient_col, date_col = None, None, None
    if col_map is not None:
        drug_col = next((c for c, cat in col_map.items() if cat == "drug_name" and c in df.columns), None)
        patient_col = next((c for c, cat in col_map.items() if cat == "patient_id" and c in df.columns), None)
        date_col = next((c for c, cat in col_map.items() if cat == "date" and c in df.columns), None)
    
    data.append(["", "", ""])
    data.append(["Column Analysis", "", ""])
    
    if drug_col:
        unique_drugs = df[drug_col].nunique()
        data.append(["Unique Drugs", f"{unique_drugs:,}", f"Column: {drug_col}"])
    
    if patient_col:
        unique_patients = df[patient_col].nunique()
        data.append(["Unique Patients", f"{unique_patients:,}", f"Column: {patient_col}"])
    
    if date_col:
        date_range = f"{df[date_col].min()} to {df[date_col].max()}"
        data.append(["Date Range", date_range, f"Column: {date_col}"])
    
    # Domain characteristics
    data.append(["", "", ""])
    data.append(["Domain Characteristics", "", ""])
    data.append(["Domain", "Healthcare/Pharmaceutical", "Prescription analysis"])
    data.append(["Data Type", "Clinical Prescription Data", "Drug prescription patterns"])
    data.append(["Analysis Focus", "Multi-model ML analysis", "Risk, patterns, trends, anomalies"])
    
    return data


def create_models_table(results):
    """Create Table 2: ML/DL models used."""
    data = []
    data.append(["Model Type", "Algorithm", "Purpose", "Category"])
    
    if results is None:
        return data
    
    # Risk Analysis Model
    if results.get("risk"):
        data.append(["Deep Learning", "PyTorch MLP", "Risk classification", "Supervised Learning"])
    
    # Cohort Analysis Model
    if results.get("cohort"):
        data.append(["Machine Learning", "KMeans Clustering", "Patient cohort identification", "Unsupervised Learning"])
    
    # Anomaly Detection Model
    if results.get("anomaly"):
        data.append(["Deep Learning", "PyTorch Autoencoder", "Anomaly detection", "Unsupervised Learning"])
    
    # Trend Analysis Model
    if results.get("trend") and isinstance(results["trend"], dict):
        trend_model = results["trend"].get("metrics", {}).get("Model", "Holt-Winters")
        data.append(["Time Series", trend_model, "Trend forecasting", "Time Series Analysis"])
    
    # Pattern Analysis Model
    if results.get("pattern"):
        data.append(["Association Rules", "Apriori-lite", "Co-prescription patterns", "Pattern Mining"])
    
    # LLM Model
    data.append(["Large Language Model", "Phi-4 mini", "Clinical insights generation", "Natural Language Processing"])
    
    return data


def create_metrics_table(results):
    """Create Table 3: Accuracy and metrics of models."""
    data = []
    data.append(["Model", "Accuracy/Performance", "Key Metrics", "Execution Time"])
    
    if results is None:
        return data
    
    for agent_key, result in results.items():
        if result and isinstance(result, dict) and result.get("status") == "ok" and result.get("metrics"):
            metrics = result["metrics"]
            model_name = metrics.get("Model", agent_key.title())
            
            # Get main performance metric
            performance = "N/A"
            if "Accuracy" in metrics:
                performance = metrics["Accuracy"]
            elif "Silhouette" in metrics:
                performance = metrics["Silhouette"]
            elif "Confidence" in metrics:
                performance = metrics["Confidence"]
            
            # Get additional metrics
            additional_metrics = []
            for metric_name in ["Precision", "Recall", "RMSE", "MAE", "Variance"]:
                if metric_name in metrics:
                    additional_metrics.append(f"{metric_name}: {metrics[metric_name]}")
            
            additional_str = ", ".join(additional_metrics) if additional_metrics else "N/A"
            execution_time = metrics.get("Execution", "N/A")
            
            data.append([model_name, performance, additional_str, execution_time])
    
    return data


def create_statistical_validation_table(validation_results):
    """Create Table 4: Statistical validation results with enhanced formatting."""
    data = []
    data.append(["Agent Name", "Model Name", "Test Variable", "Group Variable", "Test", "Statistic", "P-value", "P-value (corrected)", "Effect Size", "Effect Type", "Significant"])
    
    if validation_results is None:
        return data
    
    # Check if we have validation data from advanced cohort agent
    if hasattr(validation_results, 'get') and 'validation_table' in validation_results:
        # Use the validation table from advanced cohort agent
        validation_df = validation_results['validation_table']
        if not validation_df.empty:
            for _, row in validation_df.iterrows():
                # Format values for better readability
                agent_name = str(row.get('Agent Name', 'N/A')).strip()
                model_name = str(row.get('Model Name', 'N/A')).strip()
                test_var = str(row.get('Test Variable', 'N/A')).strip()
                group_var = str(row.get('Group Variable', 'N/A')).strip()
                test_name = str(row.get('Test', 'N/A')).strip()
                statistic = str(row.get('Statistic', 'N/A')).strip()
                p_value = str(row.get('P-value', 'N/A')).strip()
                p_corrected = str(row.get('P-value (corrected)', 'N/A')).strip()
                effect_size = str(row.get('Effect Size', 'N/A')).strip()
                effect_type = str(row.get('Effect Type', 'N/A')).strip()
                significant = str(row.get('Significant', 'N/A')).strip()
                
                data.append([
                    agent_name, model_name, test_var, group_var, test_name, statistic, p_value, p_corrected, effect_size, effect_type, significant
                ])
    else:
        # Fallback to old validation method for backward compatibility
        # T-test results
        if "t_test" in validation_results:
            for var, results_dict in validation_results["t_test"].items():
                if "error" not in results_dict:
                    t_stat = results_dict["t_statistic"]
                    p_val = results_dict["p_value"]
                    cohens_d = results_dict["cohens_d"]
                    significant = "Yes" if results_dict["significant"] else "No"
                    
                    data.append([
                        "Risk Agent",
                        "Classification Model",
                        var,
                        "Risk Groups",
                        "Independent T-test",
                        f"t = {t_stat:.3f}",
                        f"p = {p_val:.4f}",
                        f"p = {p_val:.4f}",
                        f"d = {cohens_d:.3f}",
                        "Cohen's d",
                        significant
                    ])
        
        # ANOVA results
        if "anova" in validation_results:
            for var, results_dict in validation_results["anova"].items():
                if "error" not in results_dict:
                    f_stat = results_dict["f_statistic"]
                    p_val = results_dict["p_value"]
                    significant = "Yes" if results_dict["significant"] else "No"
                    
                    data.append([
                        "Cohort Agent",
                        "Clustering Model",
                        var,
                        "Cohort Groups",
                        "One-way ANOVA",
                        f"F = {f_stat:.3f}",
                        f"p = {p_val:.4f}",
                        f"p = {p_val:.4f}",
                        f"η² = {results_dict['eta_squared']:.3f}",
                        "Effect Size",
                        significant
                    ])
    
    return data



def _fig_to_pdf_image(fig, width=400, height=300):
    """Converts a plotly figure to a reportlab Image."""
    from reportlab.platypus import Image as RLImage
    import tempfile
    import os
    if fig is None:
        return None
    try:
        # Save to temp file
        fd, path = tempfile.mkstemp(suffix=".png")
        os.close(fd)
        fig.write_image(path, format="png", engine="kaleido", width=800, height=600)
        img = RLImage(path, width=width, height=height)
        return img
    except Exception as e:
        print(f"Error generating chart image: {e}")
        return None

def _get_benchmark_chart(tool_key, leaderboard):
    """Creates a plotly chart for model benchmarking."""
    import pandas as pd
    import plotly.express as px
    if not leaderboard or not isinstance(leaderboard, list):
        return None
    valid_records = [c for c in leaderboard if isinstance(c, dict) and c.get("valid", False)]
    if not valid_records:
        valid_records = [c for c in leaderboard if isinstance(c, dict)]
    if not valid_records:
        return None
    df_board = pd.DataFrame(valid_records)
    tool_key = tool_key.lower()
    try:
        if "trend" in tool_key and "rmse" in df_board.columns:
            plot_df = df_board[df_board["rmse"].fillna(999999) < 90000].copy()
            if plot_df.empty: plot_df = df_board.copy()
            fig = px.bar(plot_df, x="model", y="rmse", color="is_winner" if "is_winner" in plot_df.columns else None, title="Trend Model RMSE (Lower is Better)", text=plot_df["rmse"].round(2))
        elif "cohort" in tool_key and "silhouette" in df_board.columns:
            fig = px.bar(df_board, x="model", y="silhouette", color="is_winner" if "is_winner" in df_board.columns else None, title="Clustering Silhouette Score (Higher is Better)", text=df_board["silhouette"].round(2))
        elif "risk" in tool_key and "roc_auc" in df_board.columns:
            fig = px.bar(df_board, x="model", y="roc_auc", color="is_winner" if "is_winner" in df_board.columns else None, title="Risk Model ROC-AUC (Higher is Better)", text=df_board["roc_auc"].round(2))
        elif "anomaly" in tool_key and "separation_score" in df_board.columns:
            fig = px.bar(df_board, x="model", y="separation_score", color="is_winner" if "is_winner" in df_board.columns else None, title="Anomaly Separation Score (Higher is Better)", text=df_board["separation_score"].round(2))
        else:
            return None
        
        fig.update_layout(showlegend=False, margin=dict(l=20, r=20, t=40, b=20))
        return fig
    except Exception as e:
        print(f"Error creating chart: {e}")
        return None

def generate_pdf_report(df, col_map, results, llm_insights=None, dynamic_summary=None, mapping_details=None):
    """Generate comprehensive 9-section PDF report."""
    import io
    from datetime import datetime
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.units import inch

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=24, spaceAfter=20, alignment=1, textColor=colors.darkblue)
    heading_style = ParagraphStyle('CustomHeading', parent=styles['Heading2'], fontSize=16, spaceAfter=10, textColor=colors.darkblue)
    sub_heading = ParagraphStyle('SubHeading', parent=styles['Heading3'], fontSize=12, spaceAfter=8, textColor=colors.dimgrey)
    normal_style = styles['Normal']
    
    content = []
    
    # Title Page
    content.append(Paragraph("Prescription Trend AI: Clinical Intelligence Report", title_style))
    content.append(Paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", normal_style))
    content.append(Spacer(1, 30))
    
    # 1. Summary & Data
    content.append(Paragraph("1. Summary & Data", heading_style))
    if dynamic_summary:
        content.append(Paragraph(dynamic_summary, normal_style))
    else:
        content.append(Paragraph(f"Dataset encompasses {len(df):,} records across {len(df.columns)} dimensions.", normal_style))
    content.append(Spacer(1, 10))
    
    # 2. Canonical Schema & Evidence
    content.append(Paragraph("2. Canonical Schema & Evidence", heading_style))
    if mapping_details:
        map_data = [["Dataset Column", "Canonical Concept", "Confidence", "Evidence"]]
        for col, d in mapping_details.items():
            map_data.append([
                col[:20], 
                d.get("canonical", "OTHER"), 
                f"{int(d.get('confidence', 0)*100)}%", 
                d.get("evidence", "")[:40] + "..."
            ])
        t = Table(map_data, colWidths=[1.5*inch, 1.2*inch, 0.8*inch, 3.0*inch])
        t.setStyle(TableStyle([('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2E4088')), ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke), ('ALIGN', (0,0), (-1,-1), 'LEFT'), ('GRID', (0,0), (-1,-1), 1, colors.grey)]))
        content.append(t)
    else:
        content.append(Paragraph("Mapping details not available.", normal_style))
    content.append(Spacer(1, 20))
    
    # 3. Dynamic Model Selection
    content.append(Paragraph("3. Dynamic Model Selection", heading_style))
    content.append(Paragraph("Model competition results for each executed analytical tool.", normal_style))
    content.append(Spacer(1, 10))
    
    has_charts = False
    if results:
        for tool_name, result in results.items():
            if result.get("status") == "ok" and "leaderboard" in result:
                fig = _get_benchmark_chart(tool_name, result["leaderboard"])
                if fig:
                    img = _fig_to_pdf_image(fig, width=400, height=250)
                    if img:
                        content.append(Paragraph(f"{tool_name.replace('_tool', '').title()} Model Performance", sub_heading))
                        content.append(img)
                        content.append(Spacer(1, 15))
                        has_charts = True
    if not has_charts:
        content.append(Paragraph("No dynamic model competition charts available.", normal_style))
    content.append(PageBreak())
    
    # 4. Risk Stratification
    content.append(Paragraph("4. Risk Stratification", heading_style))
    risk_res = results.get("risk_tool", {}) if results else {}
    if risk_res.get("status") == "ok":
        content.append(Paragraph("Risk tool executed successfully. Significant risk patterns identified.", normal_style))
        # Add a table of feature importances if they exist
        findings = risk_res.get("findings", [])
        for finding in findings:
            content.append(Paragraph(f"• {finding}", normal_style))
    else:
        content.append(Paragraph("Risk analysis not performed or insufficient data.", normal_style))
    content.append(Spacer(1, 20))
    
    # 5. Cohort Phenotypes
    content.append(Paragraph("5. Cohort Phenotypes", heading_style))
    cohort_res = results.get("cohort_tool", {}) if results else {}
    if cohort_res.get("status") == "ok":
        for finding in cohort_res.get("findings", []):
            content.append(Paragraph(f"• {finding}", normal_style))
    else:
        content.append(Paragraph("Cohort analysis not performed.", normal_style))
    content.append(Spacer(1, 20))
    
    # 6. Anomaly Detection
    content.append(Paragraph("6. Anomaly Detection", heading_style))
    anomaly_res = results.get("anomaly_tool", {}) if results else {}
    if anomaly_res.get("status") == "ok":
        for finding in anomaly_res.get("findings", []):
            content.append(Paragraph(f"• {finding}", normal_style))
    else:
        content.append(Paragraph("Anomaly analysis not performed.", normal_style))
    content.append(Spacer(1, 20))
    
    # 7. Co-Prescriptions
    content.append(Paragraph("7. Co-Prescriptions", heading_style))
    pattern_res = results.get("pattern_tool", {}) if results else {}
    if pattern_res.get("status") == "ok":
        for finding in pattern_res.get("findings", []):
            content.append(Paragraph(f"• {finding}", normal_style))
    else:
        content.append(Paragraph("Co-prescription pattern mining not performed.", normal_style))
    content.append(Spacer(1, 20))
    
    # 8. Temporal Trends
    content.append(Paragraph("8. Temporal Trends", heading_style))
    trend_res = results.get("trend_tool", {}) if results else {}
    if trend_res.get("status") == "ok":
        for finding in trend_res.get("findings", []):
            content.append(Paragraph(f"• {finding}", normal_style))
    else:
        content.append(Paragraph("Temporal trend forecasting not performed.", normal_style))
    content.append(PageBreak())
    
    # 9. AI Executive Synthesis
    content.append(Paragraph("9. AI Executive Synthesis", heading_style))
    if llm_insights and "ERROR_OLLAMA_DOWN" not in llm_insights:
        insights_style = ParagraphStyle('Insights', parent=styles['Normal'], backColor=colors.HexColor('#F8F9FA'), borderColor=colors.HexColor('#E0E0E0'), borderWidth=1, borderPadding=10, fontSize=10, leading=14)
        # Parse newlines correctly
        for para in llm_insights.split('\n'):
            if para.strip():
                content.append(Paragraph(para.strip(), insights_style))
                content.append(Spacer(1, 5))
    else:
        content.append(Paragraph("AI synthesis unavailable (Ollama server may be down).", normal_style))
        
    doc.build(content)
    return buffer.getvalue()
